// gribi_aft.enums is generated by proto_generator as a protobuf
// representation of a YANG schema.
//
// Input schema modules:
//  - github.com/openconfig/gribi/v1/yang/gribi-aft.yang
// Include paths:
//   - github.com/openconfig/gribi/v1/yang/...
//   - github.com/openconfig/gribi/v1/yang/deps/...

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: v1/proto/gribi_aft/enums/enums.proto

package enums

import (
	_ "github.com/openconfig/ygot/proto/yext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenconfigAftTypesEncapsulationHeaderType represents an enumerated type generated for the YANG enumerated type encapsulation-header-type.
type OpenconfigAftTypesEncapsulationHeaderType int32

const (
	OpenconfigAftTypesEncapsulationHeaderType_OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UNSET OpenconfigAftTypesEncapsulationHeaderType = 0
	OpenconfigAftTypesEncapsulationHeaderType_OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_GRE   OpenconfigAftTypesEncapsulationHeaderType = 1
	OpenconfigAftTypesEncapsulationHeaderType_OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_IPV4  OpenconfigAftTypesEncapsulationHeaderType = 2
	OpenconfigAftTypesEncapsulationHeaderType_OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_IPV6  OpenconfigAftTypesEncapsulationHeaderType = 3
	OpenconfigAftTypesEncapsulationHeaderType_OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_MPLS  OpenconfigAftTypesEncapsulationHeaderType = 4
	OpenconfigAftTypesEncapsulationHeaderType_OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_VXLAN OpenconfigAftTypesEncapsulationHeaderType = 5
	OpenconfigAftTypesEncapsulationHeaderType_OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDP   OpenconfigAftTypesEncapsulationHeaderType = 6
	OpenconfigAftTypesEncapsulationHeaderType_OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDPV4 OpenconfigAftTypesEncapsulationHeaderType = 7
	OpenconfigAftTypesEncapsulationHeaderType_OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDPV6 OpenconfigAftTypesEncapsulationHeaderType = 8
)

// Enum value maps for OpenconfigAftTypesEncapsulationHeaderType.
var (
	OpenconfigAftTypesEncapsulationHeaderType_name = map[int32]string{
		0: "OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UNSET",
		1: "OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_GRE",
		2: "OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_IPV4",
		3: "OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_IPV6",
		4: "OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_MPLS",
		5: "OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_VXLAN",
		6: "OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDP",
		7: "OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDPV4",
		8: "OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDPV6",
	}
	OpenconfigAftTypesEncapsulationHeaderType_value = map[string]int32{
		"OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UNSET": 0,
		"OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_GRE":   1,
		"OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_IPV4":  2,
		"OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_IPV6":  3,
		"OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_MPLS":  4,
		"OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_VXLAN": 5,
		"OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDP":   6,
		"OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDPV4": 7,
		"OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDPV6": 8,
	}
)

func (x OpenconfigAftTypesEncapsulationHeaderType) Enum() *OpenconfigAftTypesEncapsulationHeaderType {
	p := new(OpenconfigAftTypesEncapsulationHeaderType)
	*p = x
	return p
}

func (x OpenconfigAftTypesEncapsulationHeaderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenconfigAftTypesEncapsulationHeaderType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_gribi_aft_enums_enums_proto_enumTypes[0].Descriptor()
}

func (OpenconfigAftTypesEncapsulationHeaderType) Type() protoreflect.EnumType {
	return &file_v1_proto_gribi_aft_enums_enums_proto_enumTypes[0]
}

func (x OpenconfigAftTypesEncapsulationHeaderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenconfigAftTypesEncapsulationHeaderType.Descriptor instead.
func (OpenconfigAftTypesEncapsulationHeaderType) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_gribi_aft_enums_enums_proto_rawDescGZIP(), []int{0}
}

// OpenconfigMplsTypesMplsLabelEnum represents an enumerated type generated for the YANG enumerated type mpls-label.
type OpenconfigMplsTypesMplsLabelEnum int32

const (
	OpenconfigMplsTypesMplsLabelEnum_OPENCONFIGMPLSTYPESMPLSLABELENUM_UNSET                   OpenconfigMplsTypesMplsLabelEnum = 0
	OpenconfigMplsTypesMplsLabelEnum_OPENCONFIGMPLSTYPESMPLSLABELENUM_IPV4_EXPLICIT_NULL      OpenconfigMplsTypesMplsLabelEnum = 1
	OpenconfigMplsTypesMplsLabelEnum_OPENCONFIGMPLSTYPESMPLSLABELENUM_ROUTER_ALERT            OpenconfigMplsTypesMplsLabelEnum = 2
	OpenconfigMplsTypesMplsLabelEnum_OPENCONFIGMPLSTYPESMPLSLABELENUM_IPV6_EXPLICIT_NULL      OpenconfigMplsTypesMplsLabelEnum = 3
	OpenconfigMplsTypesMplsLabelEnum_OPENCONFIGMPLSTYPESMPLSLABELENUM_IMPLICIT_NULL           OpenconfigMplsTypesMplsLabelEnum = 4
	OpenconfigMplsTypesMplsLabelEnum_OPENCONFIGMPLSTYPESMPLSLABELENUM_ENTROPY_LABEL_INDICATOR OpenconfigMplsTypesMplsLabelEnum = 8
	OpenconfigMplsTypesMplsLabelEnum_OPENCONFIGMPLSTYPESMPLSLABELENUM_NO_LABEL                OpenconfigMplsTypesMplsLabelEnum = 9
)

// Enum value maps for OpenconfigMplsTypesMplsLabelEnum.
var (
	OpenconfigMplsTypesMplsLabelEnum_name = map[int32]string{
		0: "OPENCONFIGMPLSTYPESMPLSLABELENUM_UNSET",
		1: "OPENCONFIGMPLSTYPESMPLSLABELENUM_IPV4_EXPLICIT_NULL",
		2: "OPENCONFIGMPLSTYPESMPLSLABELENUM_ROUTER_ALERT",
		3: "OPENCONFIGMPLSTYPESMPLSLABELENUM_IPV6_EXPLICIT_NULL",
		4: "OPENCONFIGMPLSTYPESMPLSLABELENUM_IMPLICIT_NULL",
		8: "OPENCONFIGMPLSTYPESMPLSLABELENUM_ENTROPY_LABEL_INDICATOR",
		9: "OPENCONFIGMPLSTYPESMPLSLABELENUM_NO_LABEL",
	}
	OpenconfigMplsTypesMplsLabelEnum_value = map[string]int32{
		"OPENCONFIGMPLSTYPESMPLSLABELENUM_UNSET":                   0,
		"OPENCONFIGMPLSTYPESMPLSLABELENUM_IPV4_EXPLICIT_NULL":      1,
		"OPENCONFIGMPLSTYPESMPLSLABELENUM_ROUTER_ALERT":            2,
		"OPENCONFIGMPLSTYPESMPLSLABELENUM_IPV6_EXPLICIT_NULL":      3,
		"OPENCONFIGMPLSTYPESMPLSLABELENUM_IMPLICIT_NULL":           4,
		"OPENCONFIGMPLSTYPESMPLSLABELENUM_ENTROPY_LABEL_INDICATOR": 8,
		"OPENCONFIGMPLSTYPESMPLSLABELENUM_NO_LABEL":                9,
	}
)

func (x OpenconfigMplsTypesMplsLabelEnum) Enum() *OpenconfigMplsTypesMplsLabelEnum {
	p := new(OpenconfigMplsTypesMplsLabelEnum)
	*p = x
	return p
}

func (x OpenconfigMplsTypesMplsLabelEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenconfigMplsTypesMplsLabelEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_gribi_aft_enums_enums_proto_enumTypes[1].Descriptor()
}

func (OpenconfigMplsTypesMplsLabelEnum) Type() protoreflect.EnumType {
	return &file_v1_proto_gribi_aft_enums_enums_proto_enumTypes[1]
}

func (x OpenconfigMplsTypesMplsLabelEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenconfigMplsTypesMplsLabelEnum.Descriptor instead.
func (OpenconfigMplsTypesMplsLabelEnum) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_gribi_aft_enums_enums_proto_rawDescGZIP(), []int{1}
}

// OpenconfigPacketMatchTypesIPPROTOCOL represents an enumerated type generated for the YANG identity IP_PROTOCOL.
type OpenconfigPacketMatchTypesIPPROTOCOL int32

const (
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_UNSET    OpenconfigPacketMatchTypesIPPROTOCOL = 0
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_GRE   OpenconfigPacketMatchTypesIPPROTOCOL = 24050007
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_TCP   OpenconfigPacketMatchTypesIPPROTOCOL = 38721802
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_L2TP  OpenconfigPacketMatchTypesIPPROTOCOL = 81903923
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_AUTH  OpenconfigPacketMatchTypesIPPROTOCOL = 203904199
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_PIM   OpenconfigPacketMatchTypesIPPROTOCOL = 272904165
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_IN_IP OpenconfigPacketMatchTypesIPPROTOCOL = 309674436
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_IGMP  OpenconfigPacketMatchTypesIPPROTOCOL = 512271866
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_ICMP  OpenconfigPacketMatchTypesIPPROTOCOL = 512860246
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_UDP   OpenconfigPacketMatchTypesIPPROTOCOL = 525100026
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_RSVP  OpenconfigPacketMatchTypesIPPROTOCOL = 530070378
)

// Enum value maps for OpenconfigPacketMatchTypesIPPROTOCOL.
var (
	OpenconfigPacketMatchTypesIPPROTOCOL_name = map[int32]string{
		0:         "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_UNSET",
		24050007:  "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_GRE",
		38721802:  "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_TCP",
		81903923:  "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_L2TP",
		203904199: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_AUTH",
		272904165: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_PIM",
		309674436: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_IN_IP",
		512271866: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_IGMP",
		512860246: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_ICMP",
		525100026: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_UDP",
		530070378: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_RSVP",
	}
	OpenconfigPacketMatchTypesIPPROTOCOL_value = map[string]int32{
		"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_UNSET":    0,
		"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_GRE":   24050007,
		"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_TCP":   38721802,
		"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_L2TP":  81903923,
		"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_AUTH":  203904199,
		"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_PIM":   272904165,
		"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_IN_IP": 309674436,
		"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_IGMP":  512271866,
		"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_ICMP":  512860246,
		"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_UDP":   525100026,
		"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_RSVP":  530070378,
	}
)

func (x OpenconfigPacketMatchTypesIPPROTOCOL) Enum() *OpenconfigPacketMatchTypesIPPROTOCOL {
	p := new(OpenconfigPacketMatchTypesIPPROTOCOL)
	*p = x
	return p
}

func (x OpenconfigPacketMatchTypesIPPROTOCOL) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenconfigPacketMatchTypesIPPROTOCOL) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_gribi_aft_enums_enums_proto_enumTypes[2].Descriptor()
}

func (OpenconfigPacketMatchTypesIPPROTOCOL) Type() protoreflect.EnumType {
	return &file_v1_proto_gribi_aft_enums_enums_proto_enumTypes[2]
}

func (x OpenconfigPacketMatchTypesIPPROTOCOL) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenconfigPacketMatchTypesIPPROTOCOL.Descriptor instead.
func (OpenconfigPacketMatchTypesIPPROTOCOL) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_gribi_aft_enums_enums_proto_rawDescGZIP(), []int{2}
}

var File_v1_proto_gribi_aft_enums_enums_proto protoreflect.FileDescriptor

const file_v1_proto_gribi_aft_enums_enums_proto_rawDesc = "" +
	"\n" +
	"$v1/proto/gribi_aft/enums/enums.proto\x12\x0fgribi_aft.enums\x1a0github.com/openconfig/ygot/proto/yext/yext.proto*\xca\x04\n" +
	")OpenconfigAftTypesEncapsulationHeaderType\x123\n" +
	"/OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UNSET\x10\x00\x129\n" +
	"-OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_GRE\x10\x01\x1a\x06\x82A\x03GRE\x12;\n" +
	".OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_IPV4\x10\x02\x1a\a\x82A\x04IPV4\x12;\n" +
	".OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_IPV6\x10\x03\x1a\a\x82A\x04IPV6\x12;\n" +
	".OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_MPLS\x10\x04\x1a\a\x82A\x04MPLS\x12=\n" +
	"/OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_VXLAN\x10\x05\x1a\b\x82A\x05VXLAN\x129\n" +
	"-OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDP\x10\x06\x1a\x06\x82A\x03UDP\x12=\n" +
	"/OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDPV4\x10\a\x1a\b\x82A\x05UDPV4\x12=\n" +
	"/OPENCONFIGAFTTYPESENCAPSULATIONHEADERTYPE_UDPV6\x10\b\x1a\b\x82A\x05UDPV6*\x8e\x04\n" +
	" OpenconfigMplsTypesMplsLabelEnum\x12*\n" +
	"&OPENCONFIGMPLSTYPESMPLSLABELENUM_UNSET\x10\x00\x12N\n" +
	"3OPENCONFIGMPLSTYPESMPLSLABELENUM_IPV4_EXPLICIT_NULL\x10\x01\x1a\x15\x82A\x12IPV4_EXPLICIT_NULL\x12B\n" +
	"-OPENCONFIGMPLSTYPESMPLSLABELENUM_ROUTER_ALERT\x10\x02\x1a\x0f\x82A\fROUTER_ALERT\x12N\n" +
	"3OPENCONFIGMPLSTYPESMPLSLABELENUM_IPV6_EXPLICIT_NULL\x10\x03\x1a\x15\x82A\x12IPV6_EXPLICIT_NULL\x12D\n" +
	".OPENCONFIGMPLSTYPESMPLSLABELENUM_IMPLICIT_NULL\x10\x04\x1a\x10\x82A\rIMPLICIT_NULL\x12X\n" +
	"8OPENCONFIGMPLSTYPESMPLSLABELENUM_ENTROPY_LABEL_INDICATOR\x10\b\x1a\x1a\x82A\x17ENTROPY_LABEL_INDICATOR\x12:\n" +
	")OPENCONFIGMPLSTYPESMPLSLABELENUM_NO_LABEL\x10\t\x1a\v\x82A\bNO_LABEL*\xe0\x05\n" +
	"$OpenconfigPacketMatchTypesIPPROTOCOL\x12.\n" +
	"*OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_UNSET\x10\x00\x12=\n" +
	"+OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_GRE\x10\xd7\xf2\xbb\v\x1a\t\x82A\x06IP_GRE\x12=\n" +
	"+OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_TCP\x10\x8a\xb2\xbb\x12\x1a\t\x82A\x06IP_TCP\x12?\n" +
	",OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_L2TP\x10\xb3\x82\x87'\x1a\n" +
	"\x82A\aIP_L2TP\x12?\n" +
	",OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_AUTH\x10ǩ\x9da\x1a\n" +
	"\x82A\aIP_AUTH\x12>\n" +
	"+OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_PIM\x10\xe5ߐ\x82\x01\x1a\t\x82A\x06IP_PIM\x12B\n" +
	"-OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_IN_IP\x10ăՓ\x01\x1a\v\x82A\bIP_IN_IP\x12@\n" +
	",OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_IGMP\x10\xfaˢ\xf4\x01\x1a\n" +
	"\x82A\aIP_IGMP\x12@\n" +
	",OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_ICMP\x10\xd6\xc0\xc6\xf4\x01\x1a\n" +
	"\x82A\aIP_ICMP\x12>\n" +
	"+OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_UDP\x10\xfaǱ\xfa\x01\x1a\t\x82A\x06IP_UDP\x12@\n" +
	",OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_RSVP\x10\xea\xf6\xe0\xfc\x01\x1a\n" +
	"\x82A\aIP_RSVPB6Z4github.com/openconfig/gribi/v1/proto/gribi_aft/enumsb\x06proto3"

var (
	file_v1_proto_gribi_aft_enums_enums_proto_rawDescOnce sync.Once
	file_v1_proto_gribi_aft_enums_enums_proto_rawDescData []byte
)

func file_v1_proto_gribi_aft_enums_enums_proto_rawDescGZIP() []byte {
	file_v1_proto_gribi_aft_enums_enums_proto_rawDescOnce.Do(func() {
		file_v1_proto_gribi_aft_enums_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_proto_gribi_aft_enums_enums_proto_rawDesc), len(file_v1_proto_gribi_aft_enums_enums_proto_rawDesc)))
	})
	return file_v1_proto_gribi_aft_enums_enums_proto_rawDescData
}

var file_v1_proto_gribi_aft_enums_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_v1_proto_gribi_aft_enums_enums_proto_goTypes = []any{
	(OpenconfigAftTypesEncapsulationHeaderType)(0), // 0: gribi_aft.enums.OpenconfigAftTypesEncapsulationHeaderType
	(OpenconfigMplsTypesMplsLabelEnum)(0),          // 1: gribi_aft.enums.OpenconfigMplsTypesMplsLabelEnum
	(OpenconfigPacketMatchTypesIPPROTOCOL)(0),      // 2: gribi_aft.enums.OpenconfigPacketMatchTypesIPPROTOCOL
}
var file_v1_proto_gribi_aft_enums_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_proto_gribi_aft_enums_enums_proto_init() }
func file_v1_proto_gribi_aft_enums_enums_proto_init() {
	if File_v1_proto_gribi_aft_enums_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_proto_gribi_aft_enums_enums_proto_rawDesc), len(file_v1_proto_gribi_aft_enums_enums_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_proto_gribi_aft_enums_enums_proto_goTypes,
		DependencyIndexes: file_v1_proto_gribi_aft_enums_enums_proto_depIdxs,
		EnumInfos:         file_v1_proto_gribi_aft_enums_enums_proto_enumTypes,
	}.Build()
	File_v1_proto_gribi_aft_enums_enums_proto = out.File
	file_v1_proto_gribi_aft_enums_enums_proto_goTypes = nil
	file_v1_proto_gribi_aft_enums_enums_proto_depIdxs = nil
}
