// Copyright 2020 The OpenConfig Contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: v1/proto/service/gribi.proto

package gribi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRIBI_Modify_FullMethodName = "/gribi.gRIBI/Modify"
	GRIBI_Get_FullMethodName    = "/gribi.gRIBI/Get"
	GRIBI_Flush_FullMethodName  = "/gribi.gRIBI/Flush"
)

// GRIBIClient is the client API for GRIBI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRIBI is a gRPC service which provides an external entity a mechanism through
// which to programmatically inject and remove entries from the system's RIB.
type GRIBIClient interface {
	// Modify provides a bidirectional streaming RPC that can be used to issue
	// modifications to the AFT in the form of ModifyRequest(s).
	// The network element responds (asynchronously) with a ModifyResponse
	// for each ModifyRequest indicating what action was taken, once each
	// Operation within the request has been completed.
	Modify(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ModifyRequest, ModifyResponse], error)
	// Get provides a client a means to retrieve the contents of the installed
	// AFTs from the gRIBI daemon. The client requests a Get, and the server
	// responds with the set of currently installed entries (that have been ACK'd
	// according to the underlying resource to be programmed to) via the
	// GetResponse stream. Once all entries have been sent, the server closes the
	// RPC.
	//
	// The Get RPC is typically used to allow reconcilation between a client and
	// a server or for periodical consistency checking.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error)
	// Flush allows a client to remove all entries currently installed on the
	// server via gRIBI. The client requests a Flush, and the server removes all
	// entries that match the context described by the FlushRequest.
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
}

type gRIBIClient struct {
	cc grpc.ClientConnInterface
}

func NewGRIBIClient(cc grpc.ClientConnInterface) GRIBIClient {
	return &gRIBIClient{cc}
}

func (c *gRIBIClient) Modify(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ModifyRequest, ModifyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRIBI_ServiceDesc.Streams[0], GRIBI_Modify_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ModifyRequest, ModifyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRIBI_ModifyClient = grpc.BidiStreamingClient[ModifyRequest, ModifyResponse]

func (c *gRIBIClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRIBI_ServiceDesc.Streams[1], GRIBI_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, GetResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRIBI_GetClient = grpc.ServerStreamingClient[GetResponse]

func (c *gRIBIClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, GRIBI_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRIBIServer is the server API for GRIBI service.
// All implementations must embed UnimplementedGRIBIServer
// for forward compatibility.
//
// gRIBI is a gRPC service which provides an external entity a mechanism through
// which to programmatically inject and remove entries from the system's RIB.
type GRIBIServer interface {
	// Modify provides a bidirectional streaming RPC that can be used to issue
	// modifications to the AFT in the form of ModifyRequest(s).
	// The network element responds (asynchronously) with a ModifyResponse
	// for each ModifyRequest indicating what action was taken, once each
	// Operation within the request has been completed.
	Modify(grpc.BidiStreamingServer[ModifyRequest, ModifyResponse]) error
	// Get provides a client a means to retrieve the contents of the installed
	// AFTs from the gRIBI daemon. The client requests a Get, and the server
	// responds with the set of currently installed entries (that have been ACK'd
	// according to the underlying resource to be programmed to) via the
	// GetResponse stream. Once all entries have been sent, the server closes the
	// RPC.
	//
	// The Get RPC is typically used to allow reconcilation between a client and
	// a server or for periodical consistency checking.
	Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error
	// Flush allows a client to remove all entries currently installed on the
	// server via gRIBI. The client requests a Flush, and the server removes all
	// entries that match the context described by the FlushRequest.
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	mustEmbedUnimplementedGRIBIServer()
}

// UnimplementedGRIBIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRIBIServer struct{}

func (UnimplementedGRIBIServer) Modify(grpc.BidiStreamingServer[ModifyRequest, ModifyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (UnimplementedGRIBIServer) Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGRIBIServer) Flush(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedGRIBIServer) mustEmbedUnimplementedGRIBIServer() {}
func (UnimplementedGRIBIServer) testEmbeddedByValue()               {}

// UnsafeGRIBIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRIBIServer will
// result in compilation errors.
type UnsafeGRIBIServer interface {
	mustEmbedUnimplementedGRIBIServer()
}

func RegisterGRIBIServer(s grpc.ServiceRegistrar, srv GRIBIServer) {
	// If the following call pancis, it indicates UnimplementedGRIBIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRIBI_ServiceDesc, srv)
}

func _GRIBI_Modify_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRIBIServer).Modify(&grpc.GenericServerStream[ModifyRequest, ModifyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRIBI_ModifyServer = grpc.BidiStreamingServer[ModifyRequest, ModifyResponse]

func _GRIBI_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRIBIServer).Get(m, &grpc.GenericServerStream[GetRequest, GetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRIBI_GetServer = grpc.ServerStreamingServer[GetResponse]

func _GRIBI_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRIBIServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRIBI_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRIBIServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRIBI_ServiceDesc is the grpc.ServiceDesc for GRIBI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRIBI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gribi.gRIBI",
	HandlerType: (*GRIBIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Flush",
			Handler:    _GRIBI_Flush_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Modify",
			Handler:       _GRIBI_Modify_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _GRIBI_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/proto/service/gribi.proto",
}
