// Code generated by protoc-gen-go.
// source: gob/gribi/proto/gribi_aft/gribi_aft.proto
// DO NOT EDIT!

/*
Package gribi_aft is a generated protocol buffer package.

It is generated from these files:
	gob/gribi/proto/gribi_aft/gribi_aft.proto

It has these top-level messages:
	Device
	Afts
*/
package gribi_aft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import ywrapper "github.com/openconfig/ygot/proto/ywrapper"
import _ "github.com/openconfig/ygot/proto/yext"
import gribi_aft_enums "gob/gribi/proto/gribi_aft/enums"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Afts_LabelEntry_PoppedMplsLabelStack int32

const (
	Afts_LabelEntry_POPPEDMPLSLABELSTACK_UNSET                   Afts_LabelEntry_PoppedMplsLabelStack = 0
	Afts_LabelEntry_POPPEDMPLSLABELSTACK_IPV4_EXPLICIT_NULL      Afts_LabelEntry_PoppedMplsLabelStack = 1
	Afts_LabelEntry_POPPEDMPLSLABELSTACK_ROUTER_ALERT            Afts_LabelEntry_PoppedMplsLabelStack = 2
	Afts_LabelEntry_POPPEDMPLSLABELSTACK_IPV6_EXPLICIT_NULL      Afts_LabelEntry_PoppedMplsLabelStack = 3
	Afts_LabelEntry_POPPEDMPLSLABELSTACK_IMPLICIT_NULL           Afts_LabelEntry_PoppedMplsLabelStack = 4
	Afts_LabelEntry_POPPEDMPLSLABELSTACK_ENTROPY_LABEL_INDICATOR Afts_LabelEntry_PoppedMplsLabelStack = 8
	Afts_LabelEntry_POPPEDMPLSLABELSTACK_NO_LABEL                Afts_LabelEntry_PoppedMplsLabelStack = 9
)

var Afts_LabelEntry_PoppedMplsLabelStack_name = map[int32]string{
	0: "POPPEDMPLSLABELSTACK_UNSET",
	1: "POPPEDMPLSLABELSTACK_IPV4_EXPLICIT_NULL",
	2: "POPPEDMPLSLABELSTACK_ROUTER_ALERT",
	3: "POPPEDMPLSLABELSTACK_IPV6_EXPLICIT_NULL",
	4: "POPPEDMPLSLABELSTACK_IMPLICIT_NULL",
	8: "POPPEDMPLSLABELSTACK_ENTROPY_LABEL_INDICATOR",
	9: "POPPEDMPLSLABELSTACK_NO_LABEL",
}
var Afts_LabelEntry_PoppedMplsLabelStack_value = map[string]int32{
	"POPPEDMPLSLABELSTACK_UNSET":                   0,
	"POPPEDMPLSLABELSTACK_IPV4_EXPLICIT_NULL":      1,
	"POPPEDMPLSLABELSTACK_ROUTER_ALERT":            2,
	"POPPEDMPLSLABELSTACK_IPV6_EXPLICIT_NULL":      3,
	"POPPEDMPLSLABELSTACK_IMPLICIT_NULL":           4,
	"POPPEDMPLSLABELSTACK_ENTROPY_LABEL_INDICATOR": 8,
	"POPPEDMPLSLABELSTACK_NO_LABEL":                9,
}

func (x Afts_LabelEntry_PoppedMplsLabelStack) String() string {
	return proto.EnumName(Afts_LabelEntry_PoppedMplsLabelStack_name, int32(x))
}
func (Afts_LabelEntry_PoppedMplsLabelStack) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 4, 0}
}

type Afts_LabelEntryKey_Label int32

const (
	Afts_LabelEntryKey_LABEL_UNSET                   Afts_LabelEntryKey_Label = 0
	Afts_LabelEntryKey_LABEL_IPV4_EXPLICIT_NULL      Afts_LabelEntryKey_Label = 1
	Afts_LabelEntryKey_LABEL_ROUTER_ALERT            Afts_LabelEntryKey_Label = 2
	Afts_LabelEntryKey_LABEL_IPV6_EXPLICIT_NULL      Afts_LabelEntryKey_Label = 3
	Afts_LabelEntryKey_LABEL_IMPLICIT_NULL           Afts_LabelEntryKey_Label = 4
	Afts_LabelEntryKey_LABEL_ENTROPY_LABEL_INDICATOR Afts_LabelEntryKey_Label = 8
	Afts_LabelEntryKey_LABEL_NO_LABEL                Afts_LabelEntryKey_Label = 9
)

var Afts_LabelEntryKey_Label_name = map[int32]string{
	0: "LABEL_UNSET",
	1: "LABEL_IPV4_EXPLICIT_NULL",
	2: "LABEL_ROUTER_ALERT",
	3: "LABEL_IPV6_EXPLICIT_NULL",
	4: "LABEL_IMPLICIT_NULL",
	8: "LABEL_ENTROPY_LABEL_INDICATOR",
	9: "LABEL_NO_LABEL",
}
var Afts_LabelEntryKey_Label_value = map[string]int32{
	"LABEL_UNSET":                   0,
	"LABEL_IPV4_EXPLICIT_NULL":      1,
	"LABEL_ROUTER_ALERT":            2,
	"LABEL_IPV6_EXPLICIT_NULL":      3,
	"LABEL_IMPLICIT_NULL":           4,
	"LABEL_ENTROPY_LABEL_INDICATOR": 8,
	"LABEL_NO_LABEL":                9,
}

func (x Afts_LabelEntryKey_Label) String() string {
	return proto.EnumName(Afts_LabelEntryKey_Label_name, int32(x))
}
func (Afts_LabelEntryKey_Label) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 5, 0}
}

type Afts_PolicyForwardingEntry_MplsLabel int32

const (
	Afts_PolicyForwardingEntry_MPLSLABEL_UNSET                   Afts_PolicyForwardingEntry_MplsLabel = 0
	Afts_PolicyForwardingEntry_MPLSLABEL_IPV4_EXPLICIT_NULL      Afts_PolicyForwardingEntry_MplsLabel = 1
	Afts_PolicyForwardingEntry_MPLSLABEL_ROUTER_ALERT            Afts_PolicyForwardingEntry_MplsLabel = 2
	Afts_PolicyForwardingEntry_MPLSLABEL_IPV6_EXPLICIT_NULL      Afts_PolicyForwardingEntry_MplsLabel = 3
	Afts_PolicyForwardingEntry_MPLSLABEL_IMPLICIT_NULL           Afts_PolicyForwardingEntry_MplsLabel = 4
	Afts_PolicyForwardingEntry_MPLSLABEL_ENTROPY_LABEL_INDICATOR Afts_PolicyForwardingEntry_MplsLabel = 8
	Afts_PolicyForwardingEntry_MPLSLABEL_NO_LABEL                Afts_PolicyForwardingEntry_MplsLabel = 9
)

var Afts_PolicyForwardingEntry_MplsLabel_name = map[int32]string{
	0: "MPLSLABEL_UNSET",
	1: "MPLSLABEL_IPV4_EXPLICIT_NULL",
	2: "MPLSLABEL_ROUTER_ALERT",
	3: "MPLSLABEL_IPV6_EXPLICIT_NULL",
	4: "MPLSLABEL_IMPLICIT_NULL",
	8: "MPLSLABEL_ENTROPY_LABEL_INDICATOR",
	9: "MPLSLABEL_NO_LABEL",
}
var Afts_PolicyForwardingEntry_MplsLabel_value = map[string]int32{
	"MPLSLABEL_UNSET":                   0,
	"MPLSLABEL_IPV4_EXPLICIT_NULL":      1,
	"MPLSLABEL_ROUTER_ALERT":            2,
	"MPLSLABEL_IPV6_EXPLICIT_NULL":      3,
	"MPLSLABEL_IMPLICIT_NULL":           4,
	"MPLSLABEL_ENTROPY_LABEL_INDICATOR": 8,
	"MPLSLABEL_NO_LABEL":                9,
}

func (x Afts_PolicyForwardingEntry_MplsLabel) String() string {
	return proto.EnumName(Afts_PolicyForwardingEntry_MplsLabel_name, int32(x))
}
func (Afts_PolicyForwardingEntry_MplsLabel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 12, 0}
}

type Device struct {
	Afts *Afts `protobuf:"bytes,35982132,opt,name=afts" json:"afts,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Device) GetAfts() *Afts {
	if m != nil {
		return m.Afts
	}
	return nil
}

type Afts struct {
	Ipv4Entry             []*Afts_Ipv4EntryKey             `protobuf:"bytes,410397655,rep,name=ipv4_entry,json=ipv4Entry" json:"ipv4_entry,omitempty"`
	Ipv6Entry             []*Afts_Ipv6EntryKey             `protobuf:"bytes,403891971,rep,name=ipv6_entry,json=ipv6Entry" json:"ipv6_entry,omitempty"`
	LabelEntry            []*Afts_LabelEntryKey            `protobuf:"bytes,153428187,rep,name=label_entry,json=labelEntry" json:"label_entry,omitempty"`
	MacEntry              []*Afts_MacEntryKey              `protobuf:"bytes,162139969,rep,name=mac_entry,json=macEntry" json:"mac_entry,omitempty"`
	NextHop               []*Afts_NextHopKey               `protobuf:"bytes,132654769,rep,name=next_hop,json=nextHop" json:"next_hop,omitempty"`
	NextHopGroup          []*Afts_NextHopGroupKey          `protobuf:"bytes,362999033,rep,name=next_hop_group,json=nextHopGroup" json:"next_hop_group,omitempty"`
	PolicyForwardingEntry []*Afts_PolicyForwardingEntryKey `protobuf:"bytes,269536139,rep,name=policy_forwarding_entry,json=policyForwardingEntry" json:"policy_forwarding_entry,omitempty"`
}

func (m *Afts) Reset()                    { *m = Afts{} }
func (m *Afts) String() string            { return proto.CompactTextString(m) }
func (*Afts) ProtoMessage()               {}
func (*Afts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Afts) GetIpv4Entry() []*Afts_Ipv4EntryKey {
	if m != nil {
		return m.Ipv4Entry
	}
	return nil
}

func (m *Afts) GetIpv6Entry() []*Afts_Ipv6EntryKey {
	if m != nil {
		return m.Ipv6Entry
	}
	return nil
}

func (m *Afts) GetLabelEntry() []*Afts_LabelEntryKey {
	if m != nil {
		return m.LabelEntry
	}
	return nil
}

func (m *Afts) GetMacEntry() []*Afts_MacEntryKey {
	if m != nil {
		return m.MacEntry
	}
	return nil
}

func (m *Afts) GetNextHop() []*Afts_NextHopKey {
	if m != nil {
		return m.NextHop
	}
	return nil
}

func (m *Afts) GetNextHopGroup() []*Afts_NextHopGroupKey {
	if m != nil {
		return m.NextHopGroup
	}
	return nil
}

func (m *Afts) GetPolicyForwardingEntry() []*Afts_PolicyForwardingEntryKey {
	if m != nil {
		return m.PolicyForwardingEntry
	}
	return nil
}

type Afts_Ipv4Entry struct {
	DecapsulateHeader gribi_aft_enums.OpenconfigAftEncapsulationHeaderType `protobuf:"varint,383809427,opt,name=decapsulate_header,json=decapsulateHeader,enum=gribi_aft.enums.OpenconfigAftEncapsulationHeaderType" json:"decapsulate_header,omitempty"`
	OctetsForwarded   *ywrapper.UintValue                                  `protobuf:"bytes,299759987,opt,name=octets_forwarded,json=octetsForwarded" json:"octets_forwarded,omitempty"`
	PacketsForwarded  *ywrapper.UintValue                                  `protobuf:"bytes,298329756,opt,name=packets_forwarded,json=packetsForwarded" json:"packets_forwarded,omitempty"`
}

func (m *Afts_Ipv4Entry) Reset()                    { *m = Afts_Ipv4Entry{} }
func (m *Afts_Ipv4Entry) String() string            { return proto.CompactTextString(m) }
func (*Afts_Ipv4Entry) ProtoMessage()               {}
func (*Afts_Ipv4Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Afts_Ipv4Entry) GetOctetsForwarded() *ywrapper.UintValue {
	if m != nil {
		return m.OctetsForwarded
	}
	return nil
}

func (m *Afts_Ipv4Entry) GetPacketsForwarded() *ywrapper.UintValue {
	if m != nil {
		return m.PacketsForwarded
	}
	return nil
}

type Afts_Ipv4EntryKey struct {
	Prefix    string          `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	Ipv4Entry *Afts_Ipv4Entry `protobuf:"bytes,2,opt,name=ipv4_entry,json=ipv4Entry" json:"ipv4_entry,omitempty"`
}

func (m *Afts_Ipv4EntryKey) Reset()                    { *m = Afts_Ipv4EntryKey{} }
func (m *Afts_Ipv4EntryKey) String() string            { return proto.CompactTextString(m) }
func (*Afts_Ipv4EntryKey) ProtoMessage()               {}
func (*Afts_Ipv4EntryKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *Afts_Ipv4EntryKey) GetIpv4Entry() *Afts_Ipv4Entry {
	if m != nil {
		return m.Ipv4Entry
	}
	return nil
}

type Afts_Ipv6Entry struct {
	DecapsulateHeader gribi_aft_enums.OpenconfigAftEncapsulationHeaderType `protobuf:"varint,328774623,opt,name=decapsulate_header,json=decapsulateHeader,enum=gribi_aft.enums.OpenconfigAftEncapsulationHeaderType" json:"decapsulate_header,omitempty"`
	OctetsForwarded   *ywrapper.UintValue                                  `protobuf:"bytes,219660135,opt,name=octets_forwarded,json=octetsForwarded" json:"octets_forwarded,omitempty"`
	PacketsForwarded  *ywrapper.UintValue                                  `protobuf:"bytes,204384952,opt,name=packets_forwarded,json=packetsForwarded" json:"packets_forwarded,omitempty"`
}

func (m *Afts_Ipv6Entry) Reset()                    { *m = Afts_Ipv6Entry{} }
func (m *Afts_Ipv6Entry) String() string            { return proto.CompactTextString(m) }
func (*Afts_Ipv6Entry) ProtoMessage()               {}
func (*Afts_Ipv6Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 2} }

func (m *Afts_Ipv6Entry) GetOctetsForwarded() *ywrapper.UintValue {
	if m != nil {
		return m.OctetsForwarded
	}
	return nil
}

func (m *Afts_Ipv6Entry) GetPacketsForwarded() *ywrapper.UintValue {
	if m != nil {
		return m.PacketsForwarded
	}
	return nil
}

type Afts_Ipv6EntryKey struct {
	Prefix    string          `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	Ipv6Entry *Afts_Ipv6Entry `protobuf:"bytes,2,opt,name=ipv6_entry,json=ipv6Entry" json:"ipv6_entry,omitempty"`
}

func (m *Afts_Ipv6EntryKey) Reset()                    { *m = Afts_Ipv6EntryKey{} }
func (m *Afts_Ipv6EntryKey) String() string            { return proto.CompactTextString(m) }
func (*Afts_Ipv6EntryKey) ProtoMessage()               {}
func (*Afts_Ipv6EntryKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 3} }

func (m *Afts_Ipv6EntryKey) GetIpv6Entry() *Afts_Ipv6Entry {
	if m != nil {
		return m.Ipv6Entry
	}
	return nil
}

type Afts_LabelEntry struct {
	OctetsForwarded      *ywrapper.UintValue                          `protobuf:"bytes,508405375,opt,name=octets_forwarded,json=octetsForwarded" json:"octets_forwarded,omitempty"`
	PacketsForwarded     *ywrapper.UintValue                          `protobuf:"bytes,399797536,opt,name=packets_forwarded,json=packetsForwarded" json:"packets_forwarded,omitempty"`
	PoppedMplsLabelStack []*Afts_LabelEntry_PoppedMplsLabelStackUnion `protobuf:"bytes,62799927,rep,name=popped_mpls_label_stack,json=poppedMplsLabelStack" json:"popped_mpls_label_stack,omitempty"`
}

func (m *Afts_LabelEntry) Reset()                    { *m = Afts_LabelEntry{} }
func (m *Afts_LabelEntry) String() string            { return proto.CompactTextString(m) }
func (*Afts_LabelEntry) ProtoMessage()               {}
func (*Afts_LabelEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 4} }

func (m *Afts_LabelEntry) GetOctetsForwarded() *ywrapper.UintValue {
	if m != nil {
		return m.OctetsForwarded
	}
	return nil
}

func (m *Afts_LabelEntry) GetPacketsForwarded() *ywrapper.UintValue {
	if m != nil {
		return m.PacketsForwarded
	}
	return nil
}

func (m *Afts_LabelEntry) GetPoppedMplsLabelStack() []*Afts_LabelEntry_PoppedMplsLabelStackUnion {
	if m != nil {
		return m.PoppedMplsLabelStack
	}
	return nil
}

type Afts_LabelEntry_PoppedMplsLabelStackUnion struct {
	PoppedMplsLabelStackPoppedmplslabelstack Afts_LabelEntry_PoppedMplsLabelStack `protobuf:"varint,516317880,opt,name=popped_mpls_label_stack_poppedmplslabelstack,json=poppedMplsLabelStackPoppedmplslabelstack,enum=gribi_aft.Afts_LabelEntry_PoppedMplsLabelStack" json:"popped_mpls_label_stack_poppedmplslabelstack,omitempty"`
	PoppedMplsLabelStackUint64               uint64                               `protobuf:"varint,510588408,opt,name=popped_mpls_label_stack_uint64,json=poppedMplsLabelStackUint64" json:"popped_mpls_label_stack_uint64,omitempty"`
}

func (m *Afts_LabelEntry_PoppedMplsLabelStackUnion) Reset() {
	*m = Afts_LabelEntry_PoppedMplsLabelStackUnion{}
}
func (m *Afts_LabelEntry_PoppedMplsLabelStackUnion) String() string { return proto.CompactTextString(m) }
func (*Afts_LabelEntry_PoppedMplsLabelStackUnion) ProtoMessage()    {}
func (*Afts_LabelEntry_PoppedMplsLabelStackUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 4, 0}
}

type Afts_LabelEntryKey struct {
	// Types that are valid to be assigned to Label:
	//	*Afts_LabelEntryKey_LabelLabel
	//	*Afts_LabelEntryKey_LabelUint64
	Label      isAfts_LabelEntryKey_Label `protobuf_oneof:"label"`
	LabelEntry *Afts_LabelEntry           `protobuf:"bytes,2,opt,name=label_entry,json=labelEntry" json:"label_entry,omitempty"`
}

func (m *Afts_LabelEntryKey) Reset()                    { *m = Afts_LabelEntryKey{} }
func (m *Afts_LabelEntryKey) String() string            { return proto.CompactTextString(m) }
func (*Afts_LabelEntryKey) ProtoMessage()               {}
func (*Afts_LabelEntryKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 5} }

type isAfts_LabelEntryKey_Label interface {
	isAfts_LabelEntryKey_Label()
}

type Afts_LabelEntryKey_LabelLabel struct {
	LabelLabel Afts_LabelEntryKey_Label `protobuf:"varint,39380472,opt,name=label_label,json=labelLabel,enum=gribi_aft.Afts_LabelEntryKey_Label,oneof"`
}
type Afts_LabelEntryKey_LabelUint64 struct {
	LabelUint64 uint64 `protobuf:"varint,369699564,opt,name=label_uint64,json=labelUint64,oneof"`
}

func (*Afts_LabelEntryKey_LabelLabel) isAfts_LabelEntryKey_Label()  {}
func (*Afts_LabelEntryKey_LabelUint64) isAfts_LabelEntryKey_Label() {}

func (m *Afts_LabelEntryKey) GetLabel() isAfts_LabelEntryKey_Label {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *Afts_LabelEntryKey) GetLabelLabel() Afts_LabelEntryKey_Label {
	if x, ok := m.GetLabel().(*Afts_LabelEntryKey_LabelLabel); ok {
		return x.LabelLabel
	}
	return Afts_LabelEntryKey_LABEL_UNSET
}

func (m *Afts_LabelEntryKey) GetLabelUint64() uint64 {
	if x, ok := m.GetLabel().(*Afts_LabelEntryKey_LabelUint64); ok {
		return x.LabelUint64
	}
	return 0
}

func (m *Afts_LabelEntryKey) GetLabelEntry() *Afts_LabelEntry {
	if m != nil {
		return m.LabelEntry
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Afts_LabelEntryKey) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Afts_LabelEntryKey_OneofMarshaler, _Afts_LabelEntryKey_OneofUnmarshaler, _Afts_LabelEntryKey_OneofSizer, []interface{}{
		(*Afts_LabelEntryKey_LabelLabel)(nil),
		(*Afts_LabelEntryKey_LabelUint64)(nil),
	}
}

func _Afts_LabelEntryKey_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Afts_LabelEntryKey)
	// label
	switch x := m.Label.(type) {
	case *Afts_LabelEntryKey_LabelLabel:
		b.EncodeVarint(39380472<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.LabelLabel))
	case *Afts_LabelEntryKey_LabelUint64:
		b.EncodeVarint(369699564<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.LabelUint64))
	case nil:
	default:
		return fmt.Errorf("Afts_LabelEntryKey.Label has unexpected type %T", x)
	}
	return nil
}

func _Afts_LabelEntryKey_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Afts_LabelEntryKey)
	switch tag {
	case 39380472: // label.label_label
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Label = &Afts_LabelEntryKey_LabelLabel{Afts_LabelEntryKey_Label(x)}
		return true, err
	case 369699564: // label.label_uint64
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Label = &Afts_LabelEntryKey_LabelUint64{x}
		return true, err
	default:
		return false, nil
	}
}

func _Afts_LabelEntryKey_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Afts_LabelEntryKey)
	// label
	switch x := m.Label.(type) {
	case *Afts_LabelEntryKey_LabelLabel:
		n += proto.SizeVarint(39380472<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.LabelLabel))
	case *Afts_LabelEntryKey_LabelUint64:
		n += proto.SizeVarint(369699564<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.LabelUint64))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Afts_MacEntry struct {
	OctetsForwarded  *ywrapper.UintValue `protobuf:"bytes,113345869,opt,name=octets_forwarded,json=octetsForwarded" json:"octets_forwarded,omitempty"`
	PacketsForwarded *ywrapper.UintValue `protobuf:"bytes,348841578,opt,name=packets_forwarded,json=packetsForwarded" json:"packets_forwarded,omitempty"`
}

func (m *Afts_MacEntry) Reset()                    { *m = Afts_MacEntry{} }
func (m *Afts_MacEntry) String() string            { return proto.CompactTextString(m) }
func (*Afts_MacEntry) ProtoMessage()               {}
func (*Afts_MacEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 6} }

func (m *Afts_MacEntry) GetOctetsForwarded() *ywrapper.UintValue {
	if m != nil {
		return m.OctetsForwarded
	}
	return nil
}

func (m *Afts_MacEntry) GetPacketsForwarded() *ywrapper.UintValue {
	if m != nil {
		return m.PacketsForwarded
	}
	return nil
}

type Afts_MacEntryKey struct {
	MacAddress string         `protobuf:"bytes,1,opt,name=mac_address,json=macAddress" json:"mac_address,omitempty"`
	MacEntry   *Afts_MacEntry `protobuf:"bytes,2,opt,name=mac_entry,json=macEntry" json:"mac_entry,omitempty"`
}

func (m *Afts_MacEntryKey) Reset()                    { *m = Afts_MacEntryKey{} }
func (m *Afts_MacEntryKey) String() string            { return proto.CompactTextString(m) }
func (*Afts_MacEntryKey) ProtoMessage()               {}
func (*Afts_MacEntryKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 7} }

func (m *Afts_MacEntryKey) GetMacEntry() *Afts_MacEntry {
	if m != nil {
		return m.MacEntry
	}
	return nil
}

type Afts_NextHop struct {
	InterfaceRef *Afts_NextHop_InterfaceRef `protobuf:"bytes,293682821,opt,name=interface_ref,json=interfaceRef" json:"interface_ref,omitempty"`
}

func (m *Afts_NextHop) Reset()                    { *m = Afts_NextHop{} }
func (m *Afts_NextHop) String() string            { return proto.CompactTextString(m) }
func (*Afts_NextHop) ProtoMessage()               {}
func (*Afts_NextHop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 8} }

func (m *Afts_NextHop) GetInterfaceRef() *Afts_NextHop_InterfaceRef {
	if m != nil {
		return m.InterfaceRef
	}
	return nil
}

type Afts_NextHop_InterfaceRef struct {
	Interface    *ywrapper.StringValue `protobuf:"bytes,269626950,opt,name=interface" json:"interface,omitempty"`
	Subinterface *ywrapper.UintValue   `protobuf:"bytes,387796466,opt,name=subinterface" json:"subinterface,omitempty"`
}

func (m *Afts_NextHop_InterfaceRef) Reset()                    { *m = Afts_NextHop_InterfaceRef{} }
func (m *Afts_NextHop_InterfaceRef) String() string            { return proto.CompactTextString(m) }
func (*Afts_NextHop_InterfaceRef) ProtoMessage()               {}
func (*Afts_NextHop_InterfaceRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 8, 0} }

func (m *Afts_NextHop_InterfaceRef) GetInterface() *ywrapper.StringValue {
	if m != nil {
		return m.Interface
	}
	return nil
}

func (m *Afts_NextHop_InterfaceRef) GetSubinterface() *ywrapper.UintValue {
	if m != nil {
		return m.Subinterface
	}
	return nil
}

type Afts_NextHopGroup struct {
	NextHop []*Afts_NextHopGroup_NextHopKey `protobuf:"bytes,211071474,rep,name=next_hop,json=nextHop" json:"next_hop,omitempty"`
}

func (m *Afts_NextHopGroup) Reset()                    { *m = Afts_NextHopGroup{} }
func (m *Afts_NextHopGroup) String() string            { return proto.CompactTextString(m) }
func (*Afts_NextHopGroup) ProtoMessage()               {}
func (*Afts_NextHopGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 9} }

func (m *Afts_NextHopGroup) GetNextHop() []*Afts_NextHopGroup_NextHopKey {
	if m != nil {
		return m.NextHop
	}
	return nil
}

type Afts_NextHopGroup_NextHop struct {
	Color  *ywrapper.UintValue `protobuf:"bytes,373738660,opt,name=color" json:"color,omitempty"`
	Weight *ywrapper.UintValue `protobuf:"bytes,202140175,opt,name=weight" json:"weight,omitempty"`
}

func (m *Afts_NextHopGroup_NextHop) Reset()                    { *m = Afts_NextHopGroup_NextHop{} }
func (m *Afts_NextHopGroup_NextHop) String() string            { return proto.CompactTextString(m) }
func (*Afts_NextHopGroup_NextHop) ProtoMessage()               {}
func (*Afts_NextHopGroup_NextHop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 9, 0} }

func (m *Afts_NextHopGroup_NextHop) GetColor() *ywrapper.UintValue {
	if m != nil {
		return m.Color
	}
	return nil
}

func (m *Afts_NextHopGroup_NextHop) GetWeight() *ywrapper.UintValue {
	if m != nil {
		return m.Weight
	}
	return nil
}

type Afts_NextHopGroup_NextHopKey struct {
	Index   uint64                     `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	NextHop *Afts_NextHopGroup_NextHop `protobuf:"bytes,2,opt,name=next_hop,json=nextHop" json:"next_hop,omitempty"`
}

func (m *Afts_NextHopGroup_NextHopKey) Reset()         { *m = Afts_NextHopGroup_NextHopKey{} }
func (m *Afts_NextHopGroup_NextHopKey) String() string { return proto.CompactTextString(m) }
func (*Afts_NextHopGroup_NextHopKey) ProtoMessage()    {}
func (*Afts_NextHopGroup_NextHopKey) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 9, 1}
}

func (m *Afts_NextHopGroup_NextHopKey) GetNextHop() *Afts_NextHopGroup_NextHop {
	if m != nil {
		return m.NextHop
	}
	return nil
}

type Afts_NextHopGroupKey struct {
	Id           uint64             `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	NextHopGroup *Afts_NextHopGroup `protobuf:"bytes,2,opt,name=next_hop_group,json=nextHopGroup" json:"next_hop_group,omitempty"`
}

func (m *Afts_NextHopGroupKey) Reset()                    { *m = Afts_NextHopGroupKey{} }
func (m *Afts_NextHopGroupKey) String() string            { return proto.CompactTextString(m) }
func (*Afts_NextHopGroupKey) ProtoMessage()               {}
func (*Afts_NextHopGroupKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 10} }

func (m *Afts_NextHopGroupKey) GetNextHopGroup() *Afts_NextHopGroup {
	if m != nil {
		return m.NextHopGroup
	}
	return nil
}

type Afts_NextHopKey struct {
	Index   uint64        `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	NextHop *Afts_NextHop `protobuf:"bytes,2,opt,name=next_hop,json=nextHop" json:"next_hop,omitempty"`
}

func (m *Afts_NextHopKey) Reset()                    { *m = Afts_NextHopKey{} }
func (m *Afts_NextHopKey) String() string            { return proto.CompactTextString(m) }
func (*Afts_NextHopKey) ProtoMessage()               {}
func (*Afts_NextHopKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 11} }

func (m *Afts_NextHopKey) GetNextHop() *Afts_NextHop {
	if m != nil {
		return m.NextHop
	}
	return nil
}

type Afts_PolicyForwardingEntry struct {
	IpDscp   *ywrapper.UintValue   `protobuf:"bytes,35938351,opt,name=ip_dscp,json=ipDscp" json:"ip_dscp,omitempty"`
	IpPrefix *ywrapper.StringValue `protobuf:"bytes,455458193,opt,name=ip_prefix,json=ipPrefix" json:"ip_prefix,omitempty"`
	// Types that are valid to be assigned to IpProtocol:
	//	*Afts_PolicyForwardingEntry_IpProtocolOpenconfigpacketmatchtypesipprotocol
	//	*Afts_PolicyForwardingEntry_IpProtocolUint64
	IpProtocol isAfts_PolicyForwardingEntry_IpProtocol `protobuf_oneof:"ip_protocol"`
	L4DstPort  *ywrapper.UintValue                     `protobuf:"bytes,529012939,opt,name=l4_dst_port,json=l4DstPort" json:"l4_dst_port,omitempty"`
	L4SrcPort  *ywrapper.UintValue                     `protobuf:"bytes,372676914,opt,name=l4_src_port,json=l4SrcPort" json:"l4_src_port,omitempty"`
	MacAddress *ywrapper.StringValue                   `protobuf:"bytes,162237475,opt,name=mac_address,json=macAddress" json:"mac_address,omitempty"`
	// Types that are valid to be assigned to MplsLabel:
	//	*Afts_PolicyForwardingEntry_MplsLabelMplslabel
	//	*Afts_PolicyForwardingEntry_MplsLabelUint64
	MplsLabel        isAfts_PolicyForwardingEntry_MplsLabel `protobuf_oneof:"mpls_label"`
	MplsTc           *ywrapper.UintValue                    `protobuf:"bytes,74032635,opt,name=mpls_tc,json=mplsTc" json:"mpls_tc,omitempty"`
	OctetsForwarded  *ywrapper.UintValue                    `protobuf:"bytes,175461231,opt,name=octets_forwarded,json=octetsForwarded" json:"octets_forwarded,omitempty"`
	PacketsForwarded *ywrapper.UintValue                    `protobuf:"bytes,367761904,opt,name=packets_forwarded,json=packetsForwarded" json:"packets_forwarded,omitempty"`
}

func (m *Afts_PolicyForwardingEntry) Reset()                    { *m = Afts_PolicyForwardingEntry{} }
func (m *Afts_PolicyForwardingEntry) String() string            { return proto.CompactTextString(m) }
func (*Afts_PolicyForwardingEntry) ProtoMessage()               {}
func (*Afts_PolicyForwardingEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 12} }

type isAfts_PolicyForwardingEntry_IpProtocol interface {
	isAfts_PolicyForwardingEntry_IpProtocol()
}
type isAfts_PolicyForwardingEntry_MplsLabel interface {
	isAfts_PolicyForwardingEntry_MplsLabel()
}

type Afts_PolicyForwardingEntry_IpProtocolOpenconfigpacketmatchtypesipprotocol struct {
	IpProtocolOpenconfigpacketmatchtypesipprotocol gribi_aft_enums.OpenconfigPacketMatchTypesIPPROTOCOL `protobuf:"varint,332091131,opt,name=ip_protocol_openconfigpacketmatchtypesipprotocol,json=ipProtocolOpenconfigpacketmatchtypesipprotocol,enum=gribi_aft.enums.OpenconfigPacketMatchTypesIPPROTOCOL,oneof"`
}
type Afts_PolicyForwardingEntry_IpProtocolUint64 struct {
	IpProtocolUint64 uint64 `protobuf:"varint,451771266,opt,name=ip_protocol_uint64,json=ipProtocolUint64,oneof"`
}
type Afts_PolicyForwardingEntry_MplsLabelMplslabel struct {
	MplsLabelMplslabel Afts_PolicyForwardingEntry_MplsLabel `protobuf:"varint,311921089,opt,name=mpls_label_mplslabel,json=mplsLabelMplslabel,enum=gribi_aft.Afts_PolicyForwardingEntry_MplsLabel,oneof"`
}
type Afts_PolicyForwardingEntry_MplsLabelUint64 struct {
	MplsLabelUint64 uint64 `protobuf:"varint,399811487,opt,name=mpls_label_uint64,json=mplsLabelUint64,oneof"`
}

func (*Afts_PolicyForwardingEntry_IpProtocolOpenconfigpacketmatchtypesipprotocol) isAfts_PolicyForwardingEntry_IpProtocol() {
}
func (*Afts_PolicyForwardingEntry_IpProtocolUint64) isAfts_PolicyForwardingEntry_IpProtocol()  {}
func (*Afts_PolicyForwardingEntry_MplsLabelMplslabel) isAfts_PolicyForwardingEntry_MplsLabel() {}
func (*Afts_PolicyForwardingEntry_MplsLabelUint64) isAfts_PolicyForwardingEntry_MplsLabel()    {}

func (m *Afts_PolicyForwardingEntry) GetIpProtocol() isAfts_PolicyForwardingEntry_IpProtocol {
	if m != nil {
		return m.IpProtocol
	}
	return nil
}
func (m *Afts_PolicyForwardingEntry) GetMplsLabel() isAfts_PolicyForwardingEntry_MplsLabel {
	if m != nil {
		return m.MplsLabel
	}
	return nil
}

func (m *Afts_PolicyForwardingEntry) GetIpDscp() *ywrapper.UintValue {
	if m != nil {
		return m.IpDscp
	}
	return nil
}

func (m *Afts_PolicyForwardingEntry) GetIpPrefix() *ywrapper.StringValue {
	if m != nil {
		return m.IpPrefix
	}
	return nil
}

func (m *Afts_PolicyForwardingEntry) GetIpProtocolOpenconfigpacketmatchtypesipprotocol() gribi_aft_enums.OpenconfigPacketMatchTypesIPPROTOCOL {
	if x, ok := m.GetIpProtocol().(*Afts_PolicyForwardingEntry_IpProtocolOpenconfigpacketmatchtypesipprotocol); ok {
		return x.IpProtocolOpenconfigpacketmatchtypesipprotocol
	}
	return gribi_aft_enums.OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_UNSET
}

func (m *Afts_PolicyForwardingEntry) GetIpProtocolUint64() uint64 {
	if x, ok := m.GetIpProtocol().(*Afts_PolicyForwardingEntry_IpProtocolUint64); ok {
		return x.IpProtocolUint64
	}
	return 0
}

func (m *Afts_PolicyForwardingEntry) GetL4DstPort() *ywrapper.UintValue {
	if m != nil {
		return m.L4DstPort
	}
	return nil
}

func (m *Afts_PolicyForwardingEntry) GetL4SrcPort() *ywrapper.UintValue {
	if m != nil {
		return m.L4SrcPort
	}
	return nil
}

func (m *Afts_PolicyForwardingEntry) GetMacAddress() *ywrapper.StringValue {
	if m != nil {
		return m.MacAddress
	}
	return nil
}

func (m *Afts_PolicyForwardingEntry) GetMplsLabelMplslabel() Afts_PolicyForwardingEntry_MplsLabel {
	if x, ok := m.GetMplsLabel().(*Afts_PolicyForwardingEntry_MplsLabelMplslabel); ok {
		return x.MplsLabelMplslabel
	}
	return Afts_PolicyForwardingEntry_MPLSLABEL_UNSET
}

func (m *Afts_PolicyForwardingEntry) GetMplsLabelUint64() uint64 {
	if x, ok := m.GetMplsLabel().(*Afts_PolicyForwardingEntry_MplsLabelUint64); ok {
		return x.MplsLabelUint64
	}
	return 0
}

func (m *Afts_PolicyForwardingEntry) GetMplsTc() *ywrapper.UintValue {
	if m != nil {
		return m.MplsTc
	}
	return nil
}

func (m *Afts_PolicyForwardingEntry) GetOctetsForwarded() *ywrapper.UintValue {
	if m != nil {
		return m.OctetsForwarded
	}
	return nil
}

func (m *Afts_PolicyForwardingEntry) GetPacketsForwarded() *ywrapper.UintValue {
	if m != nil {
		return m.PacketsForwarded
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Afts_PolicyForwardingEntry) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Afts_PolicyForwardingEntry_OneofMarshaler, _Afts_PolicyForwardingEntry_OneofUnmarshaler, _Afts_PolicyForwardingEntry_OneofSizer, []interface{}{
		(*Afts_PolicyForwardingEntry_IpProtocolOpenconfigpacketmatchtypesipprotocol)(nil),
		(*Afts_PolicyForwardingEntry_IpProtocolUint64)(nil),
		(*Afts_PolicyForwardingEntry_MplsLabelMplslabel)(nil),
		(*Afts_PolicyForwardingEntry_MplsLabelUint64)(nil),
	}
}

func _Afts_PolicyForwardingEntry_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Afts_PolicyForwardingEntry)
	// ip_protocol
	switch x := m.IpProtocol.(type) {
	case *Afts_PolicyForwardingEntry_IpProtocolOpenconfigpacketmatchtypesipprotocol:
		b.EncodeVarint(332091131<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IpProtocolOpenconfigpacketmatchtypesipprotocol))
	case *Afts_PolicyForwardingEntry_IpProtocolUint64:
		b.EncodeVarint(451771266<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IpProtocolUint64))
	case nil:
	default:
		return fmt.Errorf("Afts_PolicyForwardingEntry.IpProtocol has unexpected type %T", x)
	}
	// mpls_label
	switch x := m.MplsLabel.(type) {
	case *Afts_PolicyForwardingEntry_MplsLabelMplslabel:
		b.EncodeVarint(311921089<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.MplsLabelMplslabel))
	case *Afts_PolicyForwardingEntry_MplsLabelUint64:
		b.EncodeVarint(399811487<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.MplsLabelUint64))
	case nil:
	default:
		return fmt.Errorf("Afts_PolicyForwardingEntry.MplsLabel has unexpected type %T", x)
	}
	return nil
}

func _Afts_PolicyForwardingEntry_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Afts_PolicyForwardingEntry)
	switch tag {
	case 332091131: // ip_protocol.ip_protocol_openconfigpacketmatchtypesipprotocol
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.IpProtocol = &Afts_PolicyForwardingEntry_IpProtocolOpenconfigpacketmatchtypesipprotocol{gribi_aft_enums.OpenconfigPacketMatchTypesIPPROTOCOL(x)}
		return true, err
	case 451771266: // ip_protocol.ip_protocol_uint64
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.IpProtocol = &Afts_PolicyForwardingEntry_IpProtocolUint64{x}
		return true, err
	case 311921089: // mpls_label.mpls_label_mplslabel
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.MplsLabel = &Afts_PolicyForwardingEntry_MplsLabelMplslabel{Afts_PolicyForwardingEntry_MplsLabel(x)}
		return true, err
	case 399811487: // mpls_label.mpls_label_uint64
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.MplsLabel = &Afts_PolicyForwardingEntry_MplsLabelUint64{x}
		return true, err
	default:
		return false, nil
	}
}

func _Afts_PolicyForwardingEntry_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Afts_PolicyForwardingEntry)
	// ip_protocol
	switch x := m.IpProtocol.(type) {
	case *Afts_PolicyForwardingEntry_IpProtocolOpenconfigpacketmatchtypesipprotocol:
		n += proto.SizeVarint(332091131<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.IpProtocolOpenconfigpacketmatchtypesipprotocol))
	case *Afts_PolicyForwardingEntry_IpProtocolUint64:
		n += proto.SizeVarint(451771266<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.IpProtocolUint64))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// mpls_label
	switch x := m.MplsLabel.(type) {
	case *Afts_PolicyForwardingEntry_MplsLabelMplslabel:
		n += proto.SizeVarint(311921089<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.MplsLabelMplslabel))
	case *Afts_PolicyForwardingEntry_MplsLabelUint64:
		n += proto.SizeVarint(399811487<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.MplsLabelUint64))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Afts_PolicyForwardingEntryKey struct {
	Index                 uint64                      `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	PolicyForwardingEntry *Afts_PolicyForwardingEntry `protobuf:"bytes,2,opt,name=policy_forwarding_entry,json=policyForwardingEntry" json:"policy_forwarding_entry,omitempty"`
}

func (m *Afts_PolicyForwardingEntryKey) Reset()         { *m = Afts_PolicyForwardingEntryKey{} }
func (m *Afts_PolicyForwardingEntryKey) String() string { return proto.CompactTextString(m) }
func (*Afts_PolicyForwardingEntryKey) ProtoMessage()    {}
func (*Afts_PolicyForwardingEntryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 13}
}

func (m *Afts_PolicyForwardingEntryKey) GetPolicyForwardingEntry() *Afts_PolicyForwardingEntry {
	if m != nil {
		return m.PolicyForwardingEntry
	}
	return nil
}

func init() {
	proto.RegisterType((*Device)(nil), "gribi_aft.Device")
	proto.RegisterType((*Afts)(nil), "gribi_aft.Afts")
	proto.RegisterType((*Afts_Ipv4Entry)(nil), "gribi_aft.Afts.Ipv4Entry")
	proto.RegisterType((*Afts_Ipv4EntryKey)(nil), "gribi_aft.Afts.Ipv4EntryKey")
	proto.RegisterType((*Afts_Ipv6Entry)(nil), "gribi_aft.Afts.Ipv6Entry")
	proto.RegisterType((*Afts_Ipv6EntryKey)(nil), "gribi_aft.Afts.Ipv6EntryKey")
	proto.RegisterType((*Afts_LabelEntry)(nil), "gribi_aft.Afts.LabelEntry")
	proto.RegisterType((*Afts_LabelEntry_PoppedMplsLabelStackUnion)(nil), "gribi_aft.Afts.LabelEntry.PoppedMplsLabelStackUnion")
	proto.RegisterType((*Afts_LabelEntryKey)(nil), "gribi_aft.Afts.LabelEntryKey")
	proto.RegisterType((*Afts_MacEntry)(nil), "gribi_aft.Afts.MacEntry")
	proto.RegisterType((*Afts_MacEntryKey)(nil), "gribi_aft.Afts.MacEntryKey")
	proto.RegisterType((*Afts_NextHop)(nil), "gribi_aft.Afts.NextHop")
	proto.RegisterType((*Afts_NextHop_InterfaceRef)(nil), "gribi_aft.Afts.NextHop.InterfaceRef")
	proto.RegisterType((*Afts_NextHopGroup)(nil), "gribi_aft.Afts.NextHopGroup")
	proto.RegisterType((*Afts_NextHopGroup_NextHop)(nil), "gribi_aft.Afts.NextHopGroup.NextHop")
	proto.RegisterType((*Afts_NextHopGroup_NextHopKey)(nil), "gribi_aft.Afts.NextHopGroup.NextHopKey")
	proto.RegisterType((*Afts_NextHopGroupKey)(nil), "gribi_aft.Afts.NextHopGroupKey")
	proto.RegisterType((*Afts_NextHopKey)(nil), "gribi_aft.Afts.NextHopKey")
	proto.RegisterType((*Afts_PolicyForwardingEntry)(nil), "gribi_aft.Afts.PolicyForwardingEntry")
	proto.RegisterType((*Afts_PolicyForwardingEntryKey)(nil), "gribi_aft.Afts.PolicyForwardingEntryKey")
	proto.RegisterEnum("gribi_aft.Afts_LabelEntry_PoppedMplsLabelStack", Afts_LabelEntry_PoppedMplsLabelStack_name, Afts_LabelEntry_PoppedMplsLabelStack_value)
	proto.RegisterEnum("gribi_aft.Afts_LabelEntryKey_Label", Afts_LabelEntryKey_Label_name, Afts_LabelEntryKey_Label_value)
	proto.RegisterEnum("gribi_aft.Afts_PolicyForwardingEntry_MplsLabel", Afts_PolicyForwardingEntry_MplsLabel_name, Afts_PolicyForwardingEntry_MplsLabel_value)
}

func init() { proto.RegisterFile("gob/gribi/proto/gribi_aft/gribi_aft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x59, 0x7f, 0x6c, 0xdc, 0xd4,
	0x1d, 0xaf, 0xf3, 0xfb, 0x5e, 0xd2, 0x26, 0x79, 0xb4, 0xd4, 0x35, 0x0d, 0x94, 0x94, 0x2d, 0xa9,
	0xe0, 0xee, 0xb2, 0x34, 0xbd, 0x76, 0x9d, 0x18, 0x7b, 0x97, 0x5c, 0x9a, 0x1b, 0x97, 0xdc, 0xc9,
	0xb9, 0x54, 0x20, 0x0d, 0x79, 0x8e, 0xcf, 0x77, 0xb1, 0x7a, 0x39, 0x5b, 0xb6, 0xaf, 0x49, 0x80,
	0xa1, 0xe2, 0x0d, 0x26, 0xad, 0x88, 0x0d, 0xb5, 0x62, 0x20, 0x7e, 0x55, 0x82, 0x75, 0x93, 0x36,
	0xca, 0xda, 0x0d, 0xa8, 0x98, 0x84, 0x5a, 0xa1, 0xfd, 0x90, 0x4a, 0x27, 0xad, 0x5a, 0xd7, 0x95,
	0x4d, 0x4c, 0x1a, 0x7f, 0x20, 0xed, 0x87, 0x98, 0x8a, 0x36, 0xa8, 0xca, 0x60, 0xf2, 0x7b, 0x3e,
	0xdb, 0x77, 0xb1, 0x1d, 0x27, 0x8c, 0x7f, 0x4e, 0xf6, 0xf3, 0xf7, 0xfb, 0xf9, 0xbc, 0xf7, 0x7d,
	0x9f, 0xf7, 0xde, 0xf7, 0xfb, 0x0e, 0xec, 0x28, 0xc9, 0xb3, 0xf1, 0x92, 0x2a, 0xcd, 0x4a, 0x71,
	0x45, 0x95, 0x75, 0x99, 0x3c, 0x73, 0x7c, 0x51, 0x77, 0x9e, 0x62, 0xf8, 0x0b, 0x8c, 0xd8, 0x0d,
	0xcc, 0x9e, 0x92, 0xa4, 0xcf, 0x55, 0x67, 0x63, 0x82, 0x3c, 0x1f, 0x97, 0x15, 0xb1, 0x22, 0xc8,
	0x95, 0xa2, 0x54, 0x8a, 0x2f, 0x95, 0x64, 0xdd, 0x82, 0x59, 0x5a, 0x50, 0x79, 0x45, 0x11, 0x55,
	0xfb, 0x81, 0x80, 0x30, 0x43, 0x2b, 0x7b, 0x8a, 0x8b, 0x3a, 0xfe, 0xb1, 0x3c, 0x6e, 0xf5, 0xef,
	0xa1, 0x58, 0xa9, 0xce, 0x6b, 0xe4, 0x97, 0x18, 0xf7, 0xef, 0x05, 0x6d, 0x63, 0xe2, 0x41, 0x49,
	0x10, 0xe1, 0x10, 0x68, 0xe1, 0x8b, 0xba, 0x46, 0xff, 0xfc, 0xf1, 0xa3, 0xbd, 0xdb, 0xa8, 0xc1,
	0xce, 0xe1, 0xee, 0x98, 0x33, 0x20, 0x54, 0xd4, 0xb5, 0x64, 0x87, 0x81, 0x5a, 0xe3, 0xa6, 0x0d,
	0x8b, 0x2d, 0xfb, 0x2f, 0xef, 0x05, 0x2d, 0xe6, 0x07, 0xc8, 0x03, 0x20, 0x29, 0x07, 0x47, 0x38,
	0xb1, 0xa2, 0xab, 0x4b, 0xf4, 0xa5, 0x4b, 0x7f, 0x7c, 0x83, 0xda, 0xd6, 0x3c, 0xd8, 0x39, 0xbc,
	0xb5, 0x01, 0x21, 0x96, 0x56, 0x0e, 0x8e, 0xa4, 0x4c, 0xa3, 0x3b, 0xc5, 0xa5, 0xe4, 0x36, 0x03,
	0xf5, 0x61, 0xb8, 0xb8, 0xe9, 0x1c, 0xad, 0x56, 0x24, 0x81, 0xd7, 0x74, 0xf2, 0x82, 0x91, 0xd8,
	0x88, 0x54, 0xb3, 0xb7, 0x28, 0x12, 0x16, 0xc5, 0x37, 0x7f, 0x7b, 0xee, 0x8c, 0x3f, 0x45, 0xc2,
	0x9b, 0x22, 0xe1, 0xa6, 0x48, 0xb8, 0x28, 0x88, 0x3d, 0xfc, 0x1a, 0xe8, 0x2c, 0xf3, 0xb3, 0x62,
	0xd9, 0xe2, 0xf8, 0xd3, 0xd9, 0xa3, 0x69, 0x4c, 0xd1, 0xd7, 0x48, 0x91, 0x31, 0xad, 0x6c, 0x8e,
	0x2d, 0x06, 0xba, 0x9e, 0x70, 0xcc, 0x2b, 0x65, 0x2d, 0x8e, 0x21, 0x2c, 0x70, 0x50, 0xb6, 0x2d,
	0xe1, 0x5d, 0x20, 0x32, 0xcf, 0x0b, 0x16, 0xf6, 0xd9, 0x67, 0x7f, 0x34, 0x89, 0xb1, 0x6f, 0x68,
	0xc4, 0x9e, 0xe4, 0x05, 0x1b, 0xf9, 0x06, 0x03, 0xd1, 0x04, 0x59, 0xd4, 0xe7, 0x44, 0xb5, 0x22,
	0xea, 0xf1, 0x79, 0x5e, 0xb0, 0xb0, 0x3b, 0xe6, 0x2d, 0x4b, 0x38, 0x03, 0x3a, 0x2a, 0xe2, 0xa2,
	0xce, 0xcd, 0xc9, 0x0a, 0x7d, 0xf2, 0xfc, 0xb1, 0x3b, 0x30, 0x30, 0xd3, 0x08, 0x3c, 0x25, 0x2e,
	0xea, 0x13, 0xb2, 0x52, 0x8f, 0x6b, 0xfa, 0x45, 0xe7, 0x64, 0xc5, 0x79, 0x62, 0xdb, 0x2b, 0xc4,
	0x10, 0xaa, 0x60, 0x43, 0x0d, 0x96, 0x2b, 0xa9, 0x72, 0x55, 0xa1, 0xaf, 0x5e, 0x3e, 0xfc, 0x22,
	0x89, 0xfa, 0x4d, 0x3e, 0xe8, 0xfb, 0x4c, 0x3b, 0x93, 0x62, 0xc0, 0x40, 0xb7, 0xd4, 0x53, 0x44,
	0x31, 0x46, 0xe3, 0x3b, 0xdb, 0x55, 0x71, 0x79, 0xc2, 0x27, 0x28, 0xb0, 0x59, 0x91, 0xcb, 0x92,
	0xb0, 0xc4, 0x15, 0x65, 0x75, 0x81, 0x57, 0x0b, 0x52, 0xa5, 0x64, 0xc5, 0xec, 0xf0, 0xf7, 0xdf,
	0x38, 0x44, 0xd8, 0x07, 0x1b, 0xd9, 0x73, 0xd8, 0x65, 0xdc, 0xf6, 0xb0, 0x23, 0x38, 0x6c, 0xa0,
	0x38, 0xe9, 0x06, 0x41, 0x8d, 0x3a, 0xa8, 0xcb, 0x5b, 0xac, 0xc0, 0x6e, 0x52, 0xbc, 0xd0, 0x98,
	0x13, 0xcd, 0x20, 0x62, 0xcb, 0x17, 0x3e, 0x4f, 0x01, 0x58, 0x10, 0x05, 0x5e, 0xd1, 0xaa, 0x65,
	0x5e, 0x17, 0xb9, 0x39, 0x91, 0x2f, 0x88, 0x2a, 0x7d, 0xe4, 0xbd, 0x07, 0x5f, 0xa5, 0xb6, 0x51,
	0x83, 0x1b, 0x86, 0x77, 0xb9, 0xfa, 0x48, 0xd6, 0x5b, 0xd6, 0x5e, 0xbc, 0xa8, 0xa8, 0xa7, 0x2a,
	0x35, 0x5f, 0x49, 0xae, 0x4c, 0x60, 0xe7, 0xfc, 0x92, 0x22, 0x26, 0xbf, 0x68, 0xa0, 0x44, 0xe0,
	0x9a, 0x88, 0x6b, 0x3a, 0xaf, 0x8b, 0x71, 0x17, 0x77, 0x94, 0x70, 0xb3, 0xbd, 0xae, 0x36, 0x82,
	0x08, 0xef, 0x03, 0x3d, 0xb2, 0xa0, 0x8b, 0xba, 0x56, 0x8b, 0xa6, 0x58, 0xa0, 0xdf, 0xbf, 0xf2,
	0xc1, 0xa3, 0x14, 0x5e, 0xdf, 0xd7, 0xc5, 0xec, 0xad, 0x66, 0x46, 0xaa, 0xe8, 0xfb, 0xf9, 0x72,
	0x55, 0x4c, 0xee, 0x36, 0xd0, 0x48, 0x98, 0x0e, 0x10, 0xdc, 0xa8, 0x8d, 0xcb, 0x76, 0x93, 0x96,
	0xf1, 0x5a, 0x03, 0x7c, 0x00, 0xf4, 0x2a, 0xbc, 0x70, 0xa0, 0x9e, 0xfd, 0xe9, 0xf3, 0xc7, 0x82,
	0xd8, 0xf7, 0x18, 0x68, 0x57, 0x18, 0x76, 0x0b, 0xd8, 0x45, 0xdf, 0x63, 0x35, 0xd9, 0xfc, 0xcc,
	0xcb, 0x14, 0xe8, 0x72, 0xef, 0x37, 0xf0, 0x00, 0x68, 0x53, 0x54, 0xb1, 0x28, 0x2d, 0xd2, 0x66,
	0x0f, 0x22, 0xc9, 0x69, 0x03, 0xe5, 0x82, 0xc9, 0xac, 0xbd, 0x96, 0x78, 0xdd, 0x1f, 0x6c, 0x4b,
	0x8c, 0x58, 0x8b, 0x02, 0xee, 0xa9, 0xdb, 0x12, 0x9b, 0xf0, 0x90, 0xb7, 0xf8, 0x6e, 0x87, 0xae,
	0x9d, 0x8e, 0xf9, 0x09, 0x11, 0x5a, 0x22, 0x50, 0x68, 0x7f, 0x79, 0xf7, 0xaf, 0x4f, 0xff, 0xff,
	0x84, 0xe6, 0xb5, 0x33, 0xae, 0x4a, 0x68, 0xf7, 0x7a, 0x08, 0xed, 0xdd, 0x8f, 0xdf, 0x9e, 0x0b,
	0xa9, 0xb3, 0x00, 0xfe, 0x95, 0x75, 0xf6, 0x0d, 0x2f, 0x9d, 0x9d, 0xbe, 0xf8, 0x1a, 0x1f, 0x52,
	0x66, 0x01, 0xe4, 0xab, 0x90, 0x59, 0x22, 0x9c, 0xcc, 0x3c, 0xc9, 0x7c, 0x64, 0xe6, 0x69, 0xeb,
	0x29, 0xb3, 0xc4, 0x8a, 0x32, 0x4b, 0xa4, 0x1a, 0x4e, 0x3b, 0xe6, 0x42, 0x07, 0x00, 0xce, 0x41,
	0x06, 0x75, 0x8f, 0x19, 0xfc, 0xe4, 0xcd, 0x57, 0xae, 0x04, 0x2c, 0xd6, 0x21, 0x03, 0x45, 0xbd,
	0x0f, 0xbe, 0xd0, 0x73, 0xb7, 0xe0, 0x35, 0x77, 0xc7, 0xde, 0xfa, 0xdd, 0xeb, 0x01, 0xb4, 0x5f,
	0x30, 0x50, 0x2c, 0x90, 0x36, 0xc4, 0xac, 0xc1, 0x1f, 0xe2, 0x83, 0x46, 0x51, 0xc4, 0x02, 0x67,
	0xa2, 0x70, 0xe4, 0xe0, 0xd7, 0x74, 0x5e, 0x38, 0x40, 0xbf, 0x7a, 0xe8, 0x6a, 0x1f, 0x3e, 0x67,
	0x46, 0xfc, 0x0f, 0xfe, 0x58, 0x0e, 0x3b, 0x4f, 0x2a, 0x65, 0x0d, 0x37, 0x4e, 0x9b, 0x9e, 0x33,
	0x15, 0x49, 0xae, 0xb8, 0x94, 0xed, 0xd7, 0x3f, 0xec, 0x1a, 0x35, 0xbf, 0x46, 0xc9, 0x57, 0xcc,
	0xcb, 0x6e, 0x54, 0x3c, 0x30, 0x99, 0xab, 0x14, 0xd8, 0xe2, 0x4b, 0x06, 0x8f, 0x50, 0xe0, 0x36,
	0x9f, 0x71, 0x70, 0xa4, 0xdd, 0x6c, 0xc6, 0xad, 0x64, 0x70, 0xa7, 0x7f, 0xf9, 0xe4, 0x7f, 0xc8,
	0xc6, 0x11, 0x5f, 0xe5, 0xe8, 0xd8, 0x41, 0xaf, 0xfe, 0xe5, 0x3c, 0x48, 0xe0, 0x38, 0xb8, 0xd1,
	0xaf, 0x53, 0x55, 0xa9, 0xa2, 0x27, 0x46, 0xe8, 0x0f, 0xff, 0xfe, 0x8b, 0xf7, 0xcd, 0x6e, 0xb4,
	0xb0, 0x8c, 0x17, 0xea, 0x0c, 0xb6, 0xea, 0x3f, 0xd1, 0x0c, 0x36, 0x7a, 0x75, 0x05, 0xde, 0x08,
	0x98, 0x5c, 0x36, 0x97, 0x4b, 0x8d, 0x4d, 0xe6, 0x32, 0xd3, 0x19, 0x94, 0x4c, 0x65, 0xa6, 0xf3,
	0x68, 0xf4, 0x4e, 0x6e, 0x66, 0x6a, 0x3a, 0x95, 0xef, 0x59, 0x07, 0x93, 0x60, 0xc0, 0xf3, 0x7b,
	0x3a, 0xb7, 0x7f, 0x84, 0x4b, 0xdd, 0x95, 0xcb, 0xa4, 0x47, 0xd3, 0x79, 0x6e, 0x6a, 0x26, 0x93,
	0xe9, 0xa1, 0x98, 0x4d, 0x06, 0x82, 0xcb, 0x3f, 0xc0, 0x04, 0xb8, 0xd9, 0x13, 0x83, 0xcd, 0xce,
	0xe4, 0x53, 0x2c, 0x87, 0x32, 0x29, 0x36, 0xdf, 0xd3, 0xc4, 0x74, 0x1b, 0xa8, 0xcb, 0xdd, 0x14,
	0xc4, 0x9d, 0x68, 0xe0, 0x6e, 0xae, 0x71, 0x37, 0x7c, 0x80, 0x7b, 0x40, 0xbf, 0x37, 0xc6, 0xa4,
	0xdb, 0xbd, 0x85, 0xe9, 0x31, 0xd0, 0xfa, 0xba, 0x36, 0x98, 0x01, 0xb7, 0x79, 0x7a, 0xa6, 0xa6,
	0xf2, 0x6c, 0x36, 0x77, 0x37, 0x87, 0x9b, 0xb8, 0xf4, 0xd4, 0x58, 0x7a, 0x14, 0xe5, 0xb3, 0x6c,
	0x4f, 0x07, 0xc3, 0x18, 0x68, 0xb3, 0xcf, 0x57, 0x18, 0x03, 0x7d, 0x9e, 0x68, 0x53, 0x59, 0x62,
	0xda, 0x13, 0x61, 0x3a, 0x0d, 0xd4, 0x51, 0x7b, 0x65, 0x8c, 0x16, 0xb0, 0xbe, 0x2e, 0x3b, 0x86,
	0xe9, 0x5a, 0x52, 0x8d, 0x7f, 0xe9, 0x0f, 0xcf, 0xbd, 0x03, 0xb1, 0xfa, 0xb6, 0x07, 0x26, 0xd5,
	0xe4, 0x6d, 0x62, 0x9d, 0x95, 0x41, 0xe3, 0x37, 0x38, 0x00, 0xba, 0x08, 0x94, 0xa5, 0xa1, 0x7f,
	0x5c, 0x7c, 0xe1, 0xa7, 0x58, 0x43, 0x13, 0xeb, 0x58, 0x42, 0x42, 0x64, 0x03, 0xbf, 0x54, 0x9f,
	0xc8, 0x93, 0x5d, 0x91, 0xf1, 0x27, 0x74, 0xe7, 0xe9, 0xfd, 0xaf, 0x34, 0x81, 0x56, 0xc2, 0xd7,
	0x0d, 0x3a, 0x49, 0x3c, 0x6a, 0xaa, 0xda, 0x09, 0x68, 0x2b, 0x40, 0xab, 0x90, 0xd1, 0x00, 0x80,
	0xc4, 0x69, 0x25, 0xdd, 0xb8, 0xd1, 0x43, 0x0b, 0x65, 0x07, 0xb8, 0xce, 0x72, 0x5a, 0x51, 0x19,
	0xb7, 0x83, 0x3e, 0x62, 0xba, 0x36, 0x29, 0xdc, 0x04, 0x36, 0x90, 0x26, 0x9f, 0xb9, 0x4f, 0xb6,
	0x83, 0x56, 0x1c, 0x46, 0xe6, 0x23, 0x0a, 0x74, 0xd4, 0xca, 0x18, 0x58, 0xf5, 0x38, 0x57, 0xce,
	0x7f, 0xe7, 0xe1, 0x84, 0xff, 0xfe, 0xee, 0xe4, 0xec, 0xcb, 0xab, 0x9e, 0xd0, 0x07, 0xcb, 0x92,
	0xd7, 0xc1, 0xf2, 0xb7, 0x37, 0x7f, 0x7c, 0x3c, 0xe0, 0x60, 0xd9, 0x69, 0xa0, 0xa1, 0x15, 0x88,
	0xc3, 0x24, 0x04, 0xaf, 0x51, 0xa0, 0xd3, 0x55, 0xc5, 0x41, 0x1d, 0x74, 0x9a, 0x85, 0x1f, 0x5f,
	0x28, 0xa8, 0xa2, 0xa6, 0x2d, 0x4b, 0x0a, 0x3c, 0xb8, 0xac, 0x7c, 0xc0, 0x6c, 0xb0, 0xbc, 0xee,
	0xf7, 0xb5, 0x75, 0x19, 0xb1, 0x60, 0x9e, 0x17, 0x10, 0x79, 0x86, 0xbb, 0xdc, 0xe5, 0x26, 0x59,
	0x01, 0xb4, 0x5f, 0xad, 0xe9, 0xd4, 0x92, 0xcc, 0x43, 0xcd, 0xa0, 0xdd, 0xaa, 0xe5, 0xe0, 0x22,
	0x58, 0x2f, 0x55, 0x74, 0x51, 0x2d, 0xf2, 0x82, 0xc8, 0xa9, 0x62, 0x91, 0x7e, 0xe8, 0xbf, 0xdf,
	0x7a, 0x84, 0xc4, 0xef, 0x16, 0x9f, 0xfa, 0x2f, 0x96, 0xae, 0x39, 0xb0, 0x62, 0x31, 0xb9, 0xc3,
	0x40, 0x9f, 0xf7, 0xab, 0x33, 0xe3, 0x36, 0x74, 0x54, 0x15, 0x8b, 0x6c, 0x97, 0xe4, 0x72, 0x64,
	0x3e, 0x31, 0x73, 0x2a, 0x57, 0x03, 0xd4, 0x40, 0xc4, 0x36, 0xa0, 0x7f, 0xf5, 0xe7, 0xdf, 0x1c,
	0x22, 0xdd, 0xd8, 0xe4, 0x4c, 0xe3, 0xb4, 0xae, 0x4a, 0x95, 0x12, 0x99, 0xc8, 0xbd, 0x06, 0xda,
	0x1d, 0x8e, 0xb7, 0x16, 0x6a, 0x87, 0xdd, 0xe1, 0x81, 0xf7, 0x82, 0x2e, 0xad, 0x3a, 0xeb, 0xf0,
	0x5e, 0x79, 0xea, 0xdf, 0xa7, 0x03, 0xe4, 0x73, 0xbb, 0x81, 0xf6, 0xae, 0x8e, 0xd5, 0x8d, 0xce,
	0xd6, 0x71, 0x31, 0x1f, 0xb7, 0x80, 0x2e, 0x77, 0x4d, 0x0d, 0x1f, 0xa4, 0x5c, 0x55, 0xfe, 0x95,
	0x77, 0x2e, 0x14, 0x70, 0x86, 0x32, 0x10, 0x54, 0x87, 0xbb, 0x4b, 0xfe, 0xe5, 0x21, 0xf1, 0xae,
	0xc7, 0x83, 0x6e, 0x04, 0xcc, 0x54, 0xc4, 0x16, 0x47, 0x15, 0xb4, 0x0a, 0x72, 0x59, 0x56, 0xe9,
	0x17, 0x9e, 0x7c, 0xea, 0x54, 0x40, 0x54, 0xc6, 0x0d, 0x34, 0xba, 0x46, 0x62, 0x6b, 0xcd, 0x61,
	0x1a, 0x96, 0xb0, 0xc1, 0x05, 0xd0, 0xb6, 0x20, 0x4a, 0xa5, 0x39, 0x9d, 0xfe, 0xee, 0xef, 0x4f,
	0x7e, 0xdd, 0x9f, 0x76, 0x9f, 0x81, 0xc6, 0x3e, 0x1d, 0x2d, 0xa1, 0x61, 0x2d, 0x3a, 0xe6, 0x9f,
	0x14, 0x00, 0x4e, 0x3c, 0xe1, 0x33, 0x14, 0x68, 0x95, 0x2a, 0x05, 0x91, 0x24, 0xf9, 0x2d, 0xc9,
	0x87, 0x29, 0x03, 0x19, 0xd4, 0x5a, 0x19, 0x6d, 0x15, 0x16, 0xc4, 0x5a, 0xfe, 0xbf, 0x7a, 0x10,
	0xec, 0xcd, 0x92, 0x5e, 0xc1, 0x3b, 0x5c, 0x6a, 0x69, 0x0a, 0x5c, 0xb2, 0x75, 0x52, 0x71, 0xe6,
	0xfa, 0x0c, 0x05, 0xba, 0x1b, 0x2e, 0x75, 0xa0, 0x04, 0x9a, 0xa4, 0x82, 0x35, 0xe0, 0xbb, 0x0d,
	0xb4, 0x3f, 0x54, 0x4f, 0x6b, 0x63, 0x2b, 0x84, 0x1b, 0x98, 0x54, 0x60, 0x9b, 0xa4, 0x02, 0x4c,
	0x2e, 0xbb, 0x7c, 0x22, 0xa3, 0xd8, 0x1a, 0x34, 0x8a, 0xfa, 0xcb, 0x24, 0xe6, 0xb9, 0xfa, 0x29,
	0xbb, 0xa7, 0x7e, 0xc6, 0x96, 0x2b, 0x24, 0xdc, 0x84, 0xf8, 0x45, 0x7c, 0x78, 0x59, 0xc4, 0x37,
	0xfb, 0xf4, 0xd5, 0x09, 0xf2, 0xa3, 0x1b, 0xc0, 0x26, 0xcf, 0xbb, 0x2b, 0xa8, 0x82, 0x76, 0x49,
	0xe1, 0x0a, 0x9a, 0xa0, 0xd0, 0x2f, 0x9d, 0x79, 0xac, 0xd7, 0x5f, 0xe8, 0xc8, 0x40, 0x5f, 0x5e,
	0xe5, 0x0d, 0x97, 0x3d, 0x3a, 0x25, 0x6a, 0x12, 0xb0, 0x6d, 0x92, 0x32, 0xa6, 0x09, 0x0a, 0xbc,
	0x0f, 0x44, 0x24, 0x85, 0xb3, 0x6a, 0xd7, 0xc7, 0xae, 0x3d, 0x7e, 0x39, 0x70, 0x93, 0x1d, 0x35,
	0xd0, 0x57, 0xd6, 0x4e, 0x6c, 0x95, 0xb1, 0x1d, 0x92, 0x92, 0x23, 0x85, 0xec, 0x0f, 0x28, 0x30,
	0x84, 0xd9, 0x65, 0x5d, 0x16, 0xe4, 0x32, 0xe7, 0x5c, 0x75, 0x93, 0x03, 0x76, 0x9e, 0xd7, 0x85,
	0x39, 0x7d, 0x49, 0x11, 0x35, 0x49, 0xa9, 0x19, 0xd1, 0xd7, 0x9e, 0x79, 0xf1, 0xd9, 0x95, 0x6f,
	0x41, 0x72, 0x18, 0x60, 0xd2, 0x04, 0xc8, 0x9b, 0x00, 0xe9, 0x5c, 0x8e, 0xcd, 0xe6, 0xb3, 0xa3,
	0xd9, 0xcc, 0xc4, 0x3a, 0x36, 0x66, 0xf6, 0x80, 0xc0, 0x65, 0x43, 0x50, 0xc2, 0x61, 0x00, 0xdd,
	0xdd, 0xb4, 0x52, 0x51, 0xe3, 0x83, 0x97, 0x2f, 0xd5, 0x52, 0xd1, 0x1e, 0x07, 0xd1, 0xca, 0x47,
	0x1f, 0x00, 0x9d, 0xe5, 0x11, 0xae, 0xa0, 0xe9, 0x9c, 0x22, 0xab, 0x3a, 0x7d, 0xee, 0xe4, 0xb1,
	0x8f, 0x02, 0x76, 0xcc, 0x94, 0x81, 0x92, 0x6b, 0x0c, 0x6c, 0x79, 0x24, 0x5a, 0xd0, 0xf4, 0xa8,
	0xc9, 0xc2, 0x46, 0xca, 0x23, 0x63, 0x9a, 0x9e, 0x93, 0x55, 0xdd, 0xe2, 0xd7, 0x54, 0x81, 0xf0,
	0x9f, 0x3a, 0xf5, 0xd6, 0xc9, 0xcf, 0x8c, 0x5f, 0x53, 0x05, 0x9b, 0x7f, 0x5a, 0x15, 0x30, 0xff,
	0x21, 0xaa, 0x3e, 0x05, 0x7a, 0xfe, 0x89, 0x13, 0x93, 0x41, 0xd2, 0xfa, 0x14, 0x3d, 0xf0, 0x4b,
	0x87, 0x4a, 0x60, 0xa3, 0xab, 0x14, 0xb5, 0xcb, 0x55, 0xfa, 0xec, 0x91, 0xb7, 0x8f, 0xfa, 0x94,
	0xc3, 0x9e, 0x0b, 0x33, 0x66, 0x17, 0xa2, 0x13, 0x14, 0x0b, 0xe7, 0x6b, 0x2f, 0x93, 0x35, 0x40,
	0x38, 0x04, 0x7a, 0x5d, 0x44, 0x96, 0x3c, 0x9e, 0xfb, 0xf5, 0x85, 0xd7, 0x89, 0x3c, 0x28, 0xb6,
	0xdb, 0x76, 0xb2, 0xd4, 0xa1, 0x82, 0x76, 0xec, 0xa1, 0x0b, 0xf4, 0xb5, 0x73, 0xc7, 0xb7, 0x7f,
	0x26, 0x4b, 0x1d, 0xdf, 0x35, 0xe8, 0x02, 0xdb, 0x66, 0x3e, 0xe4, 0x05, 0xf8, 0x08, 0xe5, 0x91,
	0x96, 0xbf, 0x77, 0xfc, 0xe2, 0xb4, 0x3f, 0x7b, 0xda, 0x40, 0xe3, 0xab, 0x65, 0x0f, 0x9b, 0xad,
	0x7f, 0x8f, 0xf2, 0x4a, 0xd7, 0xff, 0xf5, 0xb3, 0x13, 0x2f, 0x05, 0xe8, 0xf4, 0xab, 0x06, 0xda,
	0xb7, 0xb6, 0x0e, 0x85, 0xc8, 0xe2, 0xfb, 0xff, 0xd0, 0x04, 0x22, 0xf6, 0x5c, 0xc3, 0xeb, 0x40,
	0xb7, 0x5d, 0x01, 0xdb, 0xe5, 0xe0, 0x6e, 0xb0, 0xd5, 0x69, 0x5c, 0x4d, 0x49, 0x78, 0x2b, 0xb8,
	0xde, 0x71, 0x5c, 0xa9, 0x2c, 0x6c, 0x64, 0x09, 0x5d, 0x1a, 0x46, 0xc1, 0x66, 0x97, 0xe3, 0x8a,
	0xe5, 0x21, 0x02, 0x37, 0x3b, 0xe6, 0x6b, 0x2b, 0x11, 0xb7, 0x03, 0xe8, 0x40, 0xf8, 0x95, 0x89,
	0xeb, 0x41, 0xa7, 0x6b, 0x03, 0x4d, 0x76, 0x01, 0xe0, 0xac, 0x17, 0xe6, 0xdb, 0x4d, 0x80, 0xf6,
	0xfb, 0x33, 0x07, 0x1e, 0x6e, 0xc8, 0xb9, 0xaa, 0x06, 0x52, 0xd7, 0x7a, 0x02, 0xb9, 0x0e, 0xf6,
	0xf0, 0xce, 0x75, 0xe7, 0xfd, 0x3d, 0xfe, 0xff, 0x54, 0x91, 0xe3, 0xff, 0x73, 0xa1, 0x36, 0x14,
	0x9f, 0xbf, 0x9b, 0x66, 0xdb, 0x70, 0x84, 0x76, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x77,
	0x89, 0x3a, 0x6f, 0x1e, 0x00, 0x00,
}
