// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openconfig/gribi/proto/gribi_aft/enums/enums.proto

/*
Package gribi_aft_enums is a generated protocol buffer package.

It is generated from these files:
	github.com/openconfig/gribi/proto/gribi_aft/enums/enums.proto

It has these top-level messages:
*/
package gribi_aft_enums

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/openconfig/ygot/proto/ywrapper"
import _ "github.com/openconfig/ygot/proto/yext"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// OpenconfigAftEncapsulationHeaderType represents an enumerated type generated for the YANG enumerated type encapsulation-header-type.
type OpenconfigAftEncapsulationHeaderType int32

const (
	OpenconfigAftEncapsulationHeaderType_OPENCONFIGAFTENCAPSULATIONHEADERTYPE_UNSET OpenconfigAftEncapsulationHeaderType = 0
	OpenconfigAftEncapsulationHeaderType_OPENCONFIGAFTENCAPSULATIONHEADERTYPE_GRE   OpenconfigAftEncapsulationHeaderType = 1
	OpenconfigAftEncapsulationHeaderType_OPENCONFIGAFTENCAPSULATIONHEADERTYPE_IPV4  OpenconfigAftEncapsulationHeaderType = 2
	OpenconfigAftEncapsulationHeaderType_OPENCONFIGAFTENCAPSULATIONHEADERTYPE_IPV6  OpenconfigAftEncapsulationHeaderType = 3
	OpenconfigAftEncapsulationHeaderType_OPENCONFIGAFTENCAPSULATIONHEADERTYPE_MPLS  OpenconfigAftEncapsulationHeaderType = 4
)

var OpenconfigAftEncapsulationHeaderType_name = map[int32]string{
	0: "OPENCONFIGAFTENCAPSULATIONHEADERTYPE_UNSET",
	1: "OPENCONFIGAFTENCAPSULATIONHEADERTYPE_GRE",
	2: "OPENCONFIGAFTENCAPSULATIONHEADERTYPE_IPV4",
	3: "OPENCONFIGAFTENCAPSULATIONHEADERTYPE_IPV6",
	4: "OPENCONFIGAFTENCAPSULATIONHEADERTYPE_MPLS",
}
var OpenconfigAftEncapsulationHeaderType_value = map[string]int32{
	"OPENCONFIGAFTENCAPSULATIONHEADERTYPE_UNSET": 0,
	"OPENCONFIGAFTENCAPSULATIONHEADERTYPE_GRE":   1,
	"OPENCONFIGAFTENCAPSULATIONHEADERTYPE_IPV4":  2,
	"OPENCONFIGAFTENCAPSULATIONHEADERTYPE_IPV6":  3,
	"OPENCONFIGAFTENCAPSULATIONHEADERTYPE_MPLS":  4,
}

func (x OpenconfigAftEncapsulationHeaderType) String() string {
	return proto.EnumName(OpenconfigAftEncapsulationHeaderType_name, int32(x))
}
func (OpenconfigAftEncapsulationHeaderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

// OpenconfigAftLabelEntryLabel represents an enumerated type generated for the YANG enumerated type mpls-label.
type OpenconfigAftLabelEntryLabel int32

const (
	OpenconfigAftLabelEntryLabel_GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_UNSET                   OpenconfigAftLabelEntryLabel = 0
	OpenconfigAftLabelEntryLabel_GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IPV4_EXPLICIT_NULL      OpenconfigAftLabelEntryLabel = 1
	OpenconfigAftLabelEntryLabel_GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_ROUTER_ALERT            OpenconfigAftLabelEntryLabel = 2
	OpenconfigAftLabelEntryLabel_GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IPV6_EXPLICIT_NULL      OpenconfigAftLabelEntryLabel = 3
	OpenconfigAftLabelEntryLabel_GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IMPLICIT_NULL           OpenconfigAftLabelEntryLabel = 4
	OpenconfigAftLabelEntryLabel_GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_ENTROPY_LABEL_INDICATOR OpenconfigAftLabelEntryLabel = 8
	OpenconfigAftLabelEntryLabel_GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_NO_LABEL                OpenconfigAftLabelEntryLabel = 9
)

var OpenconfigAftLabelEntryLabel_name = map[int32]string{
	0: "GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_UNSET",
	1: "GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IPV4_EXPLICIT_NULL",
	2: "GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_ROUTER_ALERT",
	3: "GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IPV6_EXPLICIT_NULL",
	4: "GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IMPLICIT_NULL",
	8: "GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_ENTROPY_LABEL_INDICATOR",
	9: "GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_NO_LABEL",
}
var OpenconfigAftLabelEntryLabel_value = map[string]int32{
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_UNSET":                   0,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IPV4_EXPLICIT_NULL":      1,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_ROUTER_ALERT":            2,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IPV6_EXPLICIT_NULL":      3,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IMPLICIT_NULL":           4,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_ENTROPY_LABEL_INDICATOR": 8,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_NO_LABEL":                9,
}

func (x OpenconfigAftLabelEntryLabel) String() string {
	return proto.EnumName(OpenconfigAftLabelEntryLabel_name, int32(x))
}
func (OpenconfigAftLabelEntryLabel) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// OpenconfigAftLabelEntryPoppedMplsLabelStack represents an enumerated type generated for the YANG enumerated type mpls-label.
type OpenconfigAftLabelEntryPoppedMplsLabelStack int32

const (
	OpenconfigAftLabelEntryPoppedMplsLabelStack_GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_UNSET                   OpenconfigAftLabelEntryPoppedMplsLabelStack = 0
	OpenconfigAftLabelEntryPoppedMplsLabelStack_GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_IPV4_EXPLICIT_NULL      OpenconfigAftLabelEntryPoppedMplsLabelStack = 1
	OpenconfigAftLabelEntryPoppedMplsLabelStack_GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_ROUTER_ALERT            OpenconfigAftLabelEntryPoppedMplsLabelStack = 2
	OpenconfigAftLabelEntryPoppedMplsLabelStack_GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_IPV6_EXPLICIT_NULL      OpenconfigAftLabelEntryPoppedMplsLabelStack = 3
	OpenconfigAftLabelEntryPoppedMplsLabelStack_GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_IMPLICIT_NULL           OpenconfigAftLabelEntryPoppedMplsLabelStack = 4
	OpenconfigAftLabelEntryPoppedMplsLabelStack_GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_ENTROPY_LABEL_INDICATOR OpenconfigAftLabelEntryPoppedMplsLabelStack = 8
	OpenconfigAftLabelEntryPoppedMplsLabelStack_GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_NO_LABEL                OpenconfigAftLabelEntryPoppedMplsLabelStack = 9
)

var OpenconfigAftLabelEntryPoppedMplsLabelStack_name = map[int32]string{
	0: "GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_UNSET",
	1: "GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_IPV4_EXPLICIT_NULL",
	2: "GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_ROUTER_ALERT",
	3: "GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_IPV6_EXPLICIT_NULL",
	4: "GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_IMPLICIT_NULL",
	8: "GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_ENTROPY_LABEL_INDICATOR",
	9: "GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_NO_LABEL",
}
var OpenconfigAftLabelEntryPoppedMplsLabelStack_value = map[string]int32{
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_UNSET":                   0,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_IPV4_EXPLICIT_NULL":      1,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_ROUTER_ALERT":            2,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_IPV6_EXPLICIT_NULL":      3,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_IMPLICIT_NULL":           4,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_ENTROPY_LABEL_INDICATOR": 8,
	"GRIBIAFT_AFTS_MPLS_LABELENTRY_STATE_POPPEDMPLSLABELSTACK_NO_LABEL":                9,
}

func (x OpenconfigAftLabelEntryPoppedMplsLabelStack) String() string {
	return proto.EnumName(OpenconfigAftLabelEntryPoppedMplsLabelStack_name, int32(x))
}
func (OpenconfigAftLabelEntryPoppedMplsLabelStack) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2}
}

// OpenconfigAftNextHopPushedMplsLabelStack represents an enumerated type generated for the YANG enumerated type mpls-label.
type OpenconfigAftNextHopPushedMplsLabelStack int32

const (
	OpenconfigAftNextHopPushedMplsLabelStack_GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_UNSET                   OpenconfigAftNextHopPushedMplsLabelStack = 0
	OpenconfigAftNextHopPushedMplsLabelStack_GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_IPV4_EXPLICIT_NULL      OpenconfigAftNextHopPushedMplsLabelStack = 1
	OpenconfigAftNextHopPushedMplsLabelStack_GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_ROUTER_ALERT            OpenconfigAftNextHopPushedMplsLabelStack = 2
	OpenconfigAftNextHopPushedMplsLabelStack_GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_IPV6_EXPLICIT_NULL      OpenconfigAftNextHopPushedMplsLabelStack = 3
	OpenconfigAftNextHopPushedMplsLabelStack_GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_IMPLICIT_NULL           OpenconfigAftNextHopPushedMplsLabelStack = 4
	OpenconfigAftNextHopPushedMplsLabelStack_GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_ENTROPY_LABEL_INDICATOR OpenconfigAftNextHopPushedMplsLabelStack = 8
	OpenconfigAftNextHopPushedMplsLabelStack_GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_NO_LABEL                OpenconfigAftNextHopPushedMplsLabelStack = 9
)

var OpenconfigAftNextHopPushedMplsLabelStack_name = map[int32]string{
	0: "GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_UNSET",
	1: "GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_IPV4_EXPLICIT_NULL",
	2: "GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_ROUTER_ALERT",
	3: "GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_IPV6_EXPLICIT_NULL",
	4: "GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_IMPLICIT_NULL",
	8: "GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_ENTROPY_LABEL_INDICATOR",
	9: "GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_NO_LABEL",
}
var OpenconfigAftNextHopPushedMplsLabelStack_value = map[string]int32{
	"GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_UNSET":                   0,
	"GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_IPV4_EXPLICIT_NULL":      1,
	"GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_ROUTER_ALERT":            2,
	"GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_IPV6_EXPLICIT_NULL":      3,
	"GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_IMPLICIT_NULL":           4,
	"GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_ENTROPY_LABEL_INDICATOR": 8,
	"GRIBIAFT_AFTS_NEXTHOPS_NEXTHOP_STATE_PUSHEDMPLSLABELSTACK_NO_LABEL":                9,
}

func (x OpenconfigAftNextHopPushedMplsLabelStack) String() string {
	return proto.EnumName(OpenconfigAftNextHopPushedMplsLabelStack_name, int32(x))
}
func (OpenconfigAftNextHopPushedMplsLabelStack) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3}
}

// OpenconfigAftPolicyForwardingEntryMplsLabel represents an enumerated type generated for the YANG enumerated type mpls-label.
type OpenconfigAftPolicyForwardingEntryMplsLabel int32

const (
	OpenconfigAftPolicyForwardingEntryMplsLabel_GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_UNSET                   OpenconfigAftPolicyForwardingEntryMplsLabel = 0
	OpenconfigAftPolicyForwardingEntryMplsLabel_GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_IPV4_EXPLICIT_NULL      OpenconfigAftPolicyForwardingEntryMplsLabel = 1
	OpenconfigAftPolicyForwardingEntryMplsLabel_GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_ROUTER_ALERT            OpenconfigAftPolicyForwardingEntryMplsLabel = 2
	OpenconfigAftPolicyForwardingEntryMplsLabel_GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_IPV6_EXPLICIT_NULL      OpenconfigAftPolicyForwardingEntryMplsLabel = 3
	OpenconfigAftPolicyForwardingEntryMplsLabel_GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_IMPLICIT_NULL           OpenconfigAftPolicyForwardingEntryMplsLabel = 4
	OpenconfigAftPolicyForwardingEntryMplsLabel_GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_ENTROPY_LABEL_INDICATOR OpenconfigAftPolicyForwardingEntryMplsLabel = 8
	OpenconfigAftPolicyForwardingEntryMplsLabel_GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_NO_LABEL                OpenconfigAftPolicyForwardingEntryMplsLabel = 9
)

var OpenconfigAftPolicyForwardingEntryMplsLabel_name = map[int32]string{
	0: "GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_UNSET",
	1: "GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_IPV4_EXPLICIT_NULL",
	2: "GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_ROUTER_ALERT",
	3: "GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_IPV6_EXPLICIT_NULL",
	4: "GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_IMPLICIT_NULL",
	8: "GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_ENTROPY_LABEL_INDICATOR",
	9: "GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_NO_LABEL",
}
var OpenconfigAftPolicyForwardingEntryMplsLabel_value = map[string]int32{
	"GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_UNSET":                   0,
	"GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_IPV4_EXPLICIT_NULL":      1,
	"GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_ROUTER_ALERT":            2,
	"GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_IPV6_EXPLICIT_NULL":      3,
	"GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_IMPLICIT_NULL":           4,
	"GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_ENTROPY_LABEL_INDICATOR": 8,
	"GRIBIAFT_AFTS_POLICYFORWARDING_POLICYFORWARDINGENTRY_CONFIG_MPLSLABEL_NO_LABEL":                9,
}

func (x OpenconfigAftPolicyForwardingEntryMplsLabel) String() string {
	return proto.EnumName(OpenconfigAftPolicyForwardingEntryMplsLabel_name, int32(x))
}
func (OpenconfigAftPolicyForwardingEntryMplsLabel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4}
}

// OpenconfigPacketMatchTypesIPPROTOCOL represents an enumerated type generated for the YANG identity IP_PROTOCOL.
type OpenconfigPacketMatchTypesIPPROTOCOL int32

const (
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_UNSET   OpenconfigPacketMatchTypesIPPROTOCOL = 0
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_GRE  OpenconfigPacketMatchTypesIPPROTOCOL = 24050007
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_TCP  OpenconfigPacketMatchTypesIPPROTOCOL = 38721802
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_L2TP OpenconfigPacketMatchTypesIPPROTOCOL = 81903923
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_AUTH OpenconfigPacketMatchTypesIPPROTOCOL = 203904199
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_PIM  OpenconfigPacketMatchTypesIPPROTOCOL = 272904165
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_IGMP OpenconfigPacketMatchTypesIPPROTOCOL = 512271866
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_ICMP OpenconfigPacketMatchTypesIPPROTOCOL = 512860246
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_UDP  OpenconfigPacketMatchTypesIPPROTOCOL = 525100026
	OpenconfigPacketMatchTypesIPPROTOCOL_OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_RSVP OpenconfigPacketMatchTypesIPPROTOCOL = 530070378
)

var OpenconfigPacketMatchTypesIPPROTOCOL_name = map[int32]string{
	0:         "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_UNSET",
	24050007:  "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_GRE",
	38721802:  "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_TCP",
	81903923:  "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_L2TP",
	203904199: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_AUTH",
	272904165: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_PIM",
	512271866: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_IGMP",
	512860246: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_ICMP",
	525100026: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_UDP",
	530070378: "OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_RSVP",
}
var OpenconfigPacketMatchTypesIPPROTOCOL_value = map[string]int32{
	"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_UNSET":   0,
	"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_GRE":  24050007,
	"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_TCP":  38721802,
	"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_L2TP": 81903923,
	"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_AUTH": 203904199,
	"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_PIM":  272904165,
	"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_IGMP": 512271866,
	"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_ICMP": 512860246,
	"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_UDP":  525100026,
	"OPENCONFIGPACKETMATCHTYPESIPPROTOCOL_IP_RSVP": 530070378,
}

func (x OpenconfigPacketMatchTypesIPPROTOCOL) String() string {
	return proto.EnumName(OpenconfigPacketMatchTypesIPPROTOCOL_name, int32(x))
}
func (OpenconfigPacketMatchTypesIPPROTOCOL) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5}
}

// OpenconfigPolicyTypesINSTALLPROTOCOLTYPE represents an enumerated type generated for the YANG identity INSTALL_PROTOCOL_TYPE.
type OpenconfigPolicyTypesINSTALLPROTOCOLTYPE int32

const (
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_UNSET              OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 0
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_STATIC             OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 164198026
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_LOCAL_AGGREGATE    OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 167243989
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF               OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 187006448
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_ISIS               OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 308545656
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_BGP                OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 436650411
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_DIRECTLY_CONNECTED OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 463126862
	OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF3              OpenconfigPolicyTypesINSTALLPROTOCOLTYPE = 470106339
)

var OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_name = map[int32]string{
	0:         "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_UNSET",
	164198026: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_STATIC",
	167243989: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_LOCAL_AGGREGATE",
	187006448: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF",
	308545656: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_ISIS",
	436650411: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_BGP",
	463126862: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_DIRECTLY_CONNECTED",
	470106339: "OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF3",
}
var OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_value = map[string]int32{
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_UNSET":              0,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_STATIC":             164198026,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_LOCAL_AGGREGATE":    167243989,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF":               187006448,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_ISIS":               308545656,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_BGP":                436650411,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_DIRECTLY_CONNECTED": 463126862,
	"OPENCONFIGPOLICYTYPESINSTALLPROTOCOLTYPE_OSPF3":              470106339,
}

func (x OpenconfigPolicyTypesINSTALLPROTOCOLTYPE) String() string {
	return proto.EnumName(OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_name, int32(x))
}
func (OpenconfigPolicyTypesINSTALLPROTOCOLTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6}
}

func init() {
	proto.RegisterEnum("gribi_aft.enums.OpenconfigAftEncapsulationHeaderType", OpenconfigAftEncapsulationHeaderType_name, OpenconfigAftEncapsulationHeaderType_value)
	proto.RegisterEnum("gribi_aft.enums.OpenconfigAftLabelEntryLabel", OpenconfigAftLabelEntryLabel_name, OpenconfigAftLabelEntryLabel_value)
	proto.RegisterEnum("gribi_aft.enums.OpenconfigAftLabelEntryPoppedMplsLabelStack", OpenconfigAftLabelEntryPoppedMplsLabelStack_name, OpenconfigAftLabelEntryPoppedMplsLabelStack_value)
	proto.RegisterEnum("gribi_aft.enums.OpenconfigAftNextHopPushedMplsLabelStack", OpenconfigAftNextHopPushedMplsLabelStack_name, OpenconfigAftNextHopPushedMplsLabelStack_value)
	proto.RegisterEnum("gribi_aft.enums.OpenconfigAftPolicyForwardingEntryMplsLabel", OpenconfigAftPolicyForwardingEntryMplsLabel_name, OpenconfigAftPolicyForwardingEntryMplsLabel_value)
	proto.RegisterEnum("gribi_aft.enums.OpenconfigPacketMatchTypesIPPROTOCOL", OpenconfigPacketMatchTypesIPPROTOCOL_name, OpenconfigPacketMatchTypesIPPROTOCOL_value)
	proto.RegisterEnum("gribi_aft.enums.OpenconfigPolicyTypesINSTALLPROTOCOLTYPE", OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_name, OpenconfigPolicyTypesINSTALLPROTOCOLTYPE_value)
}

func init() {
	proto.RegisterFile("github.com/openconfig/gribi/proto/gribi_aft/enums/enums.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 1104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4b, 0x6c, 0xdc, 0x44,
	0x18, 0x66, 0xf3, 0x6a, 0x3a, 0x05, 0x65, 0x34, 0x12, 0x42, 0xb2, 0x38, 0x22, 0x51, 0x52, 0x48,
	0xaa, 0x26, 0x0a, 0x91, 0x20, 0x69, 0x67, 0xbd, 0xb3, 0xde, 0x51, 0xfc, 0x18, 0xec, 0xd9, 0x92,
	0x14, 0x2a, 0xcb, 0xd9, 0x38, 0x9b, 0x55, 0xd3, 0xb5, 0xd9, 0x75, 0xd4, 0xee, 0x81, 0x03, 0xe6,
	0x80, 0xd4, 0x53, 0x24, 0xd4, 0x13, 0x70, 0x41, 0xe2, 0x80, 0x38, 0xf1, 0xb8, 0xf5, 0x02, 0x07,
	0xe8, 0x01, 0x09, 0x95, 0x03, 0x70, 0x41, 0x6a, 0x11, 0xe2, 0x02, 0x42, 0x42, 0x08, 0x21, 0x14,
	0x38, 0x20, 0xdb, 0xb5, 0xd9, 0x07, 0xdb, 0xb5, 0x9d, 0xbd, 0xac, 0x66, 0xfe, 0x7f, 0xbe, 0xef,
	0xfb, 0x7f, 0xfb, 0xf3, 0xd8, 0xb3, 0x60, 0xad, 0xde, 0xf0, 0xf6, 0x0e, 0xb6, 0x17, 0x6a, 0xce,
	0xd5, 0x45, 0xc7, 0xb5, 0x9b, 0x35, 0xa7, 0xb9, 0xdb, 0xa8, 0x2f, 0xd6, 0x5b, 0x8d, 0xed, 0xc6,
	0xa2, 0xdb, 0x72, 0x3c, 0x27, 0x1a, 0x9b, 0xd6, 0xae, 0xb7, 0x68, 0x37, 0x0f, 0xae, 0xb6, 0xa3,
	0xdf, 0x85, 0x30, 0x87, 0xe6, 0x92, 0xe4, 0x42, 0x18, 0x16, 0x56, 0xff, 0x9f, 0xaf, 0x53, 0x77,
	0xbc, 0xfb, 0x74, 0x9d, 0x6b, 0x2d, 0xcb, 0x75, 0xed, 0x56, 0x32, 0x88, 0xa8, 0x84, 0xb3, 0xa3,
	0x91, 0xf6, 0x75, 0x2f, 0xfc, 0x89, 0x10, 0xf3, 0x9f, 0x4c, 0x80, 0x27, 0xb4, 0x64, 0x25, 0xde,
	0xf5, 0x48, 0xb3, 0x66, 0xb9, 0xed, 0x83, 0x7d, 0xcb, 0x6b, 0x38, 0xcd, 0x8a, 0x6d, 0xed, 0xd8,
	0x2d, 0xde, 0x71, 0x6d, 0xb4, 0x00, 0xe6, 0x35, 0x46, 0x54, 0x51, 0x53, 0xcb, 0x54, 0xc2, 0x65,
	0x4e, 0x54, 0x11, 0x33, 0xa3, 0x2a, 0x63, 0x4e, 0x35, 0xb5, 0x42, 0x70, 0x89, 0xe8, 0x7c, 0x8b,
	0x11, 0xb3, 0xaa, 0x1a, 0x84, 0xc3, 0x87, 0xd0, 0x32, 0x38, 0x9d, 0x6a, 0xbd, 0xa4, 0x13, 0x58,
	0x10, 0x66, 0x7c, 0x3c, 0x29, 0xe9, 0x04, 0xad, 0x80, 0xa7, 0x52, 0xa1, 0x28, 0xbb, 0xb8, 0x0c,
	0x27, 0x84, 0x13, 0x3e, 0x9e, 0x0a, 0x86, 0x59, 0x70, 0x2b, 0x70, 0x32, 0xc6, 0xad, 0xa4, 0xc6,
	0x29, 0x4c, 0x36, 0xe0, 0x54, 0x88, 0x0b, 0x86, 0xf3, 0x77, 0xa6, 0xc0, 0xe3, 0x3d, 0x97, 0x4d,
	0xb6, 0xb6, 0xed, 0x7d, 0xd2, 0xf4, 0x5a, 0x9d, 0x70, 0x84, 0x96, 0xc1, 0x59, 0x49, 0xa7, 0x45,
	0x8a, 0xcb, 0xdc, 0xc4, 0x65, 0x6e, 0x84, 0x0c, 0xa6, 0x8c, 0x8b, 0x44, 0x26, 0x2a, 0xd7, 0xb7,
	0xcc, 0x48, 0x32, 0x8a, 0x24, 0x17, 0x6d, 0x13, 0xac, 0x65, 0x40, 0x05, 0x9d, 0x9b, 0x64, 0x93,
	0xc9, 0x54, 0xa4, 0xdc, 0x54, 0xab, 0xb2, 0x0c, 0x0b, 0xc2, 0xa3, 0x3e, 0x46, 0x83, 0x09, 0x24,
	0x83, 0x67, 0x33, 0x30, 0xeb, 0x5a, 0x95, 0x13, 0xdd, 0xc4, 0x32, 0xd1, 0x39, 0x9c, 0x10, 0xe6,
	0x7c, 0xfc, 0x70, 0x77, 0x28, 0x7b, 0x9d, 0x2b, 0x7d, 0x75, 0x4e, 0xc6, 0x75, 0xf6, 0x25, 0x90,
	0x0a, 0x56, 0xb3, 0x30, 0x2b, 0xdd, 0xa4, 0x53, 0x02, 0xf4, 0xf1, 0x23, 0x3d, 0x31, 0xb4, 0x0d,
	0x8a, 0x19, 0xf8, 0x82, 0x90, 0xc6, 0xb6, 0x62, 0x76, 0xb5, 0x44, 0x45, 0xcc, 0x35, 0x1d, 0xce,
	0x0a, 0x82, 0x8f, 0x1f, 0x1b, 0x92, 0x45, 0x25, 0xb0, 0x94, 0x41, 0x43, 0xd5, 0xa2, 0x01, 0x3c,
	0x29, 0x9c, 0xf2, 0xf1, 0x6c, 0x3c, 0x9d, 0xff, 0x6c, 0x1a, 0x9c, 0x19, 0x62, 0x29, 0xe6, 0xb8,
	0xae, 0xbd, 0xa3, 0xb8, 0xfb, 0xed, 0x30, 0x66, 0x78, 0x56, 0xed, 0x0a, 0x2a, 0x82, 0xf5, 0x07,
	0xab, 0x1a, 0x1c, 0x73, 0x62, 0x32, 0x8d, 0x31, 0x52, 0x0a, 0x72, 0x61, 0xca, 0xe0, 0x58, 0xdc,
	0x48, 0xfc, 0xb6, 0x0b, 0x36, 0x72, 0x73, 0x64, 0x71, 0xdf, 0x25, 0x40, 0x72, 0xeb, 0x8c, 0xf2,
	0xe2, 0x31, 0x7b, 0x48, 0xed, 0xcc, 0x97, 0x41, 0x39, 0xbf, 0xce, 0x48, 0x9f, 0xba, 0x80, 0xe5,
	0x66, 0xcf, 0xe7, 0x5a, 0x1d, 0xe0, 0xdc, 0x8a, 0xc3, 0x3c, 0xfc, 0xf9, 0x34, 0x38, 0xdd, 0xe3,
	0x61, 0xd5, 0xbe, 0xee, 0x55, 0x1c, 0x97, 0x1d, 0xb4, 0xf7, 0x06, 0x0c, 0x2c, 0x82, 0xf3, 0xbd,
	0x05, 0xa8, 0x64, 0x93, 0x57, 0x34, 0x96, 0x0c, 0xe2, 0x0a, 0xaa, 0x46, 0x65, 0xa8, 0x83, 0xeb,
	0x40, 0xce, 0x4f, 0x92, 0xc5, 0xc2, 0x2f, 0xf5, 0xdf, 0xfe, 0x2c, 0x42, 0xa3, 0x3c, 0x7c, 0xdc,
	0x2e, 0x52, 0x9b, 0xf8, 0x32, 0x90, 0x8e, 0x21, 0x34, 0xd2, 0xc5, 0xaf, 0x80, 0x17, 0xf2, 0xd3,
	0xe7, 0xb3, 0xb1, 0xd1, 0xbf, 0xc1, 0x67, 0x91, 0x1c, 0xe6, 0xe3, 0xb7, 0x67, 0xfa, 0xf6, 0x62,
	0xe6, 0xec, 0x37, 0x6a, 0x9d, 0xb2, 0xd3, 0xba, 0x66, 0xb5, 0x76, 0x1a, 0xcd, 0x7a, 0xb8, 0x2d,
	0x27, 0x7e, 0x46, 0x5a, 0xff, 0x1e, 0xc4, 0x34, 0x99, 0x8a, 0x5b, 0x65, 0x4d, 0x7f, 0x11, 0xeb,
	0x25, 0xaa, 0x4a, 0x03, 0x81, 0x9e, 0x17, 0x43, 0x52, 0x55, 0x62, 0xeb, 0x36, 0xd8, 0x1c, 0x0f,
	0x61, 0x16, 0x8b, 0xd7, 0x81, 0x3e, 0x1e, 0xd1, 0x51, 0x76, 0x1f, 0x67, 0x77, 0xa9, 0xad, 0xdf,
	0x00, 0xc6, 0x98, 0x44, 0x47, 0x3e, 0x06, 0xaf, 0x82, 0xcb, 0xe3, 0x91, 0xca, 0xf7, 0x48, 0x98,
	0x40, 0x1d, 0x8f, 0xfc, 0xd0, 0xc7, 0x63, 0xba, 0xfb, 0xd0, 0xc0, 0xac, 0xda, 0x15, 0xdb, 0x53,
	0x2c, 0xaf, 0xb6, 0x17, 0x9c, 0x14, 0xda, 0x94, 0x31, 0x5d, 0xe3, 0x9a, 0xa8, 0xc9, 0xbd, 0x87,
	0x06, 0x86, 0xc5, 0x0d, 0xc2, 0x15, 0xcc, 0xc5, 0x4a, 0xf0, 0x4d, 0x6d, 0xfc, 0xb7, 0x2e, 0xb1,
	0xfd, 0x1a, 0x38, 0x93, 0x6a, 0x3d, 0x65, 0xe1, 0xb9, 0xe1, 0xbb, 0xdf, 0x6f, 0x9d, 0x12, 0x4e,
	0xfa, 0x78, 0x26, 0x9a, 0x67, 0x81, 0x73, 0x91, 0xc1, 0x1b, 0x1f, 0xdd, 0x42, 0x31, 0x9c, 0x8b,
	0x0c, 0x9d, 0x07, 0x4f, 0xa7, 0x85, 0xcb, 0xe7, 0x38, 0x83, 0x1f, 0xfb, 0x6f, 0x3c, 0x29, 0x00,
	0x1f, 0x9f, 0xb8, 0x1f, 0xc8, 0x42, 0x80, 0xab, 0xbc, 0x02, 0x6f, 0xbf, 0xff, 0x8e, 0x15, 0x13,
	0x04, 0x01, 0xb4, 0x9e, 0xbe, 0x01, 0x46, 0x15, 0xf8, 0xd3, 0xdd, 0x43, 0xbf, 0x10, 0x77, 0xc0,
	0xa8, 0x82, 0x2e, 0xa4, 0x2f, 0x80, 0x4a, 0x0a, 0x83, 0x47, 0x5f, 0xbe, 0xfb, 0x47, 0x21, 0xae,
	0x20, 0x88, 0x64, 0x62, 0x10, 0x15, 0x06, 0xbf, 0xfd, 0xf4, 0x8b, 0x2e, 0x06, 0x51, 0x61, 0x59,
	0x7a, 0xa8, 0x96, 0x18, 0x3c, 0xba, 0xfd, 0xe1, 0x51, 0xd2, 0x43, 0xb5, 0x94, 0xa9, 0x02, 0xdd,
	0xb8, 0xc8, 0xe0, 0xcf, 0x7f, 0xde, 0xfb, 0x27, 0xa9, 0x20, 0x88, 0xcc, 0x7f, 0x3d, 0xd5, 0xfd,
	0x15, 0x12, 0x6d, 0xdd, 0x91, 0x33, 0x55, 0x83, 0x63, 0x59, 0x8e, 0x29, 0x02, 0x46, 0x74, 0x0e,
	0x2c, 0x74, 0xc9, 0x85, 0xcf, 0x45, 0xa4, 0x34, 0xb8, 0x36, 0xb1, 0x29, 0x06, 0x8b, 0xa9, 0x31,
	0xc1, 0xdb, 0x87, 0x8a, 0xf0, 0xc6, 0xaf, 0xef, 0xa9, 0x61, 0x97, 0xd1, 0x1c, 0x19, 0x60, 0x35,
	0x35, 0x85, 0xac, 0x89, 0x58, 0x36, 0xb1, 0x24, 0xe9, 0x44, 0xc2, 0x9c, 0xc0, 0x6f, 0x7e, 0xb8,
	0xab, 0x09, 0xc8, 0xc7, 0x73, 0x7d, 0x09, 0xb4, 0x06, 0x9e, 0x49, 0x4d, 0xaa, 0x19, 0xac, 0x0c,
	0x7f, 0xfb, 0xfb, 0xe6, 0x56, 0x78, 0xa8, 0x0d, 0x66, 0x68, 0x3d, 0x03, 0x9c, 0x1a, 0xd4, 0x80,
	0x7f, 0x1d, 0x1e, 0xbe, 0x59, 0x88, 0x0e, 0xd3, 0x06, 0x35, 0xd0, 0xf3, 0x3d, 0x77, 0xee, 0xc1,
	0xf8, 0xa2, 0xc4, 0xe0, 0x07, 0xaf, 0xbf, 0x75, 0x27, 0x3a, 0xfa, 0x17, 0x25, 0x86, 0x2e, 0x81,
	0xe7, 0x52, 0xa3, 0x4b, 0x54, 0x27, 0x22, 0x97, 0xc3, 0x2d, 0x4b, 0x25, 0x22, 0x27, 0x25, 0xf8,
	0x95, 0xff, 0xcb, 0xf7, 0xd1, 0x9b, 0x6d, 0x30, 0x89, 0x2e, 0x64, 0xb8, 0xc9, 0xc1, 0xa5, 0x58,
	0x82, 0x3f, 0xbe, 0x76, 0xf3, 0x5e, 0x41, 0x98, 0xf5, 0xf1, 0x74, 0x38, 0xdf, 0x9e, 0x09, 0xff,
	0x2e, 0x59, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0x39, 0x83, 0x44, 0x90, 0xec, 0x11, 0x00, 0x00,
}
